### ISSUE TITLE
Most examples are outdated

### ISSUE THREAD

**Issue by cbergmiller** [FreeOpcUa/opcua-asyncio#1]
Most of the examples still use the synchronous API and won't work.

**Comment by cbergmiller** [comment]
I would like to add some usage examples to the readme page since some users struggle with basic concepts.
- How to open/close a client connection `Client` with/without context manager
- How to use the Subscription (and the returned handles for changing/unsubscribing)

**Comment by oroulet** [comment]
yes good. idea. But I don't think most examples are outdated. Most are up to date. Although going to them to ensure they follow best practices is a good idea
