### ISSUE TITLE
Discrepancy between exported xml and created structure

### ISSUE THREAD

**Issue by Vodlion** [FreeOpcUa/opcua-asyncio#1051]
**Describe the bug** <br />
A script-generated structure has its DataTypeDefinition/BaseDataType written as a BaseDataType (ns=0;i=24) and is written as not abstract.
Generated xml marks BaseDataType as Structure (ns=0;i=22) and as abstract.

**To Reproduce**<br />
1) Create data_type :

```
async def create_ur10_joints(server, idx):
    await new_struct(server, idx, "UR10Joints", [
        new_struct_field('J1', ua.VariantType.Double),
        new_struct_field('J2', ua.VariantType.Double),
        new_struct_field('J3', ua.VariantType.Double),
        new_struct_field('J4', ua.VariantType.Double),
        new_struct_field('J5', ua.VariantType.Double),
        new_struct_field('J6', ua.VariantType.Double)
    ])
    await server.load_data_type_definitions()

```
2) Create object type : 
```
async def initialize_ur10_object(server, idx):
    ur10_obj = await server.nodes.base_object_type.add_object_type(idx, "UR10")
    ur10_obj_joints = await ur10_obj.add_variable(idx, "Joints", ua.Variant(ua.UR10Joints(), ua.VariantType.ExtensionObject))

    await ur10_obj_joints.set_modelling_rule(True)

    await ur10_obj_joints.set_writable()

    await server.load_data_type_definitions()
```
3) Instantiate Object:

```
async def instantiate_ur10(server, idx, name):
    ur10_obj = await server.nodes.base_object_type.get_child(f'{idx}:UR10') 
    ur10 = await server.nodes.objects.add_object(idx, name, node._to_nodeid(ur10_obj))
   
    return ur10, target

```

4) Export nodes : 

```
    nodes = await server.get_root_node().get_children()
    customNodes = await LookForNamespaceNodes(nodes, 2)
    await server.export_xml(customNodes, "[PATH]\\nodes.xml")
```

```
async def LookForNamespaceNodes(nodes, idx, customNodes = [], ):
    for node in nodes:
        childNodes = await node.get_children()
        if len(childNodes) > 0:
            customNodes = await LookForNamespaceNodes(childNodes, idx, customNodes)
        namespace = (await node.read_browse_name()).NamespaceIndex
        if namespace == idx:
            customNodes.append(node)
    return customNodes
```

**Expected behavior**<br />
Structure's Subtype is the same in the nodeset.xml and the server.

**Screenshots**<br />

On the server exporting the nodeset :
![image](https://user-images.githubusercontent.com/19331754/192298572-67f5148a-ffa3-4586-b4ba-722eebc45576.png)

On the server importing the nodeset :
![image](https://user-images.githubusercontent.com/19331754/192298695-e2c40591-7ce5-490f-880d-1bfef0187c04.png)

The UR10 nodeset data type definition : 
![image](https://user-images.githubusercontent.com/19331754/192300042-164ebf72-aa98-4c10-92a4-3b3add9c67a8.png)

**Version**<br />
Python-Version: 3.9.4<br />
opcua-asyncio Version : 0.9.97

As i'm only getting started with opcua, I'm not sure which is supposed to be the good version, although I'd favor the first one as I can't seem to read complex types from the server importing the nodeset, while I don't have any problems with the script-generated one.

**Comment by schroeder-** [comment]
Correct is the follwoing:  Structure(ns=0;i=22)  and Abstract=False
