### ISSUE TITLE
XmlImporter trying to access self.nodes

### ISSUE THREAD

**Issue by AnyoChili** [FreeOpcUa/opcua-asyncio#1068]
**Describe the bug** <br />
Nodeset import fails due to the error
```
  File "/home/ubuntu/.local/lib/python3.11/site-packages/asyncua/server/server.py", line 616, in import_xml
    return await importer.import_xml(path, xmlstring)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.local/lib/python3.11/site-packages/asyncua/common/xmlimporter.py", line 154, in import_xml
    await self._check_if_namespace_meta_information_is_added()
  File "/home/ubuntu/.local/lib/python3.11/site-packages/asyncua/common/xmlimporter.py", line 106, in _check_if_namespace_meta_information_is_added
    obj = await self.nodes.namespaces.add_object(idx, uri, ua.ObjectIds.NamespaceMetadataType, False)
                ^^^^^^^^^^
AttributeError: 'XmlImporter' object has no attribute 'nodes'
```

**To Reproduce**<br />
Start minimal server and import a NodeSet2.xml file generated using SiOME.

**Expected behavior**<br />
Companion Specification NodeSets are imported without error.

**Version**<br />
Python-Version: 3.11
opcua-asyncio Version (e.g. master branch, 0.9): 3.9? Installed using `python3.11 -m pip install asyncua`

**Probable error**<br />
In `XmlImporter._check_if_namespace_meta_information_is_added(self)` `obj` is assigned `await self.nodes.namespaces.add_object(idx, uri, ua.ObjectIds.NamespaceMetadataType, False)`, although XmlIporter has no attribute `nodes`. Should be `obj = await self.server.nodes.namespaces.add_object(idx, uri, ua.ObjectIds.NamespaceMetadataType, False)` instead i guess.

**Comment by schroeder-** [comment]
Fix is in #1066
