### ISSUE TITLE
Unknown Datatype for Field LocationType in AutoID model

### ISSUE THREAD

**Issue by tobiajung** [FreeOpcUa/opcua-asyncio#1076]
Hello,

we are using the sync wrapper to test out an opcua server. Our code looks like the following:
```
self.client = Client(BASE_ADDRESS_OPCUA)
self.client.set_user(USERNAME)
self.client.set_password(PASSWORD)
self.client.connect()
self.client.load_data_type_definitions()
...
```
So we are trying to get the datatype definitions out of our opcua server.
However, the `load_data_type_definitions()` function returns an error we cannot fix:

> RuntimeError: Unknown datatype for field: StructureField(Name='LocationType', Description=LocalizedText(Locale=None, Text=None), DataType=NodeId(Identifier=3009, NamespaceIndex=4, NodeIdType=<NodeIdType.FourByte: 1>), ValueRank=-1, ArrayDimensions=None, MaxStringLength=0, IsOptional=True) in structure:ScanSettings, please report

If we try to connect our server via UAExpert, no errors are thrown there. So the model should be consistent. Moreover, UAExpert shows the definition of the LocationTypeEnumeration which is represented by node ns=4;i=3009:
<img width="215" alt="image" src="https://user-images.githubusercontent.com/102594442/195080988-28719622-b587-48ec-966a-a5484ee8fdfa.png">
So it should be available.
The ScanSettings Structure is defined in the AutoID information Model in the following form:
```
...
<Alias Alias="LocationTypeEnumeration">ns=1;i=3009</Alias>
...
  <UADataType NodeId="ns=1;i=3009" BrowseName="1:LocationTypeEnumeration">
    <DisplayName>LocationTypeEnumeration</DisplayName>
    <Documentation>https://reference.opcfoundation.org/v104/AutoID/v101/docs/9.2.3</Documentation>
    <References>
      <Reference ReferenceType="HasProperty">ns=1;i=6040</Reference>
      <Reference ReferenceType="HasSubtype" IsForward="false">i=29</Reference>
    </References>
    <Definition Name="1:LocationTypeEnumeration">
      <Field Name="NMEA" Value="0" />
      <Field Name="LOCAL" Value="1" />
      <Field Name="WGS84" Value="2" />
      <Field Name="NAME" Value="3" />
    </Definition>
  </UADataType>
...
  <UADataType NodeId="ns=1;i=3010" BrowseName="1:ScanSettings">
    <DisplayName>ScanSettings</DisplayName>
    <Documentation>https://reference.opcfoundation.org/v104/AutoID/v101/docs/9.3.7</Documentation>
    <References>
      <Reference ReferenceType="HasEncoding">ns=1;i=5015</Reference>
      <Reference ReferenceType="HasEncoding">ns=1;i=5016</Reference>
      <Reference ReferenceType="HasSubtype" IsForward="false">i=22</Reference>
    </References>
    <Definition Name="1:ScanSettings">
      <Field Name="Duration" DataType="Duration" />
      <Field Name="Cycles" DataType="Int32" />
      <Field Name="DataAvailable" DataType="Boolean" />
      <Field Name="LocationType" DataType="LocationTypeEnumeration" IsOptional="true" />
    </Definition>
  </UADataType>
...
```
We also noticed that the deprecated function `load_type_definitions` works fine whereas we are using the v1.04 nodeset definitions from the OPC Foundation.

Some Specs:
- Python Interpreter: Python 3.8
- Information Models: Base, Di, AutoId, our own to instantiate the an RfidReaderDeviceType

Any ideas?

**Comment by schroeder-** [comment]
The support for either load_data_type_definitions or load_type_definitions  depends on the server. 
Server supports v1.04 (DataTypeDefintion) -> load_data_type_definitions
Server supports only pre v1.04 (BSD) -> load_type_definitions
