### ISSUE TITLE
server treats uncertain as error, and sends null instead of value

### ISSUE THREAD

**Issue by JohanAR** [FreeOpcUa/opcua-asyncio#1102]
**Describe the bug** <br />
Values with status code uncertain are replaced with null values

**To Reproduce**<br />
call write_attribute_value with a value and status code for example UncertainSensorCalibration

**Expected behavior**<br />
I expect to get a data change notification containing the value and status code that I wrote.

**Version**<br />
Python-Version: 3.9<br />
opcua-asyncio Version: 1.0

The code refers to https://reference.opcfoundation.org/v104/Core/docs/Part4/7.7.1/ which says:
> The data value. If the StatusCode indicates an error then the value is to be ignored and the Server shall set it to null.

But https://reference.opcfoundation.org/v104/Core/docs/Part4/7.34.1/ says:
> Good Success   00   Indicates that the operation was successful and the associated results may be used.
   Uncertain Warning   01   Indicates that the operation was partially successful and that associated results might not be suitable for some purposes.
   Bad Failure   10   Indicates that the operation failed and any associated results cannot be used.

Which I interpret as that only "bad failure" statuses should be considered errors.

I propose changing "not value.StatusCode.is_good()" to "value.StatusCode.is_bad()", unless someone who knows more about OpcUa than me can clarify the situation.

**Comment by schroeder-** [comment]
Your proposed change would be correct. Feel free to crate a pr.
