### ISSUE TITLE
opcua-client

### ISSUE THREAD

**Issue by gchen001** [FreeOpcUa/opcua-asyncio#1115]
Hi there

Recently I found that when I upgrade opcua-asynico to the latest version, and i could not connect the server by this library using opcua-client gui, even when I tried to connect the server example. Could anyone helpe me? thanks a lot.
![image](https://user-images.githubusercontent.com/28584845/200349494-a3e45d59-d0e5-4eeb-8ee1-55c9e94b8372.png)

**Comment by oroulet** [comment]
was a bug which was fixed a few days ago. Doing a release now so that everything works again

**Comment by gchen001** [comment]
Thanks for your explaination. I guess so, because when i tested it in the uaexpert, everything works well
