### ISSUE TITLE
Python Charmers Future denial of service vulnerability 

### ISSUE THREAD

**Issue by AndreasHeine** [FreeOpcUa/opcua-asyncio#1165]
![image](https://user-images.githubusercontent.com/56362817/210723569-f4e1e986-0145-4645-a556-8de3fea65107.png)

**Comment by AndreasHeine** [comment]
https://github.com/advisories/GHSA-v3c5-jqr6-7qm8

**Comment by oroulet** [comment]
Why is that related to asyncua?

**Comment by AndreasHeine** [comment]
future is one of our dependancies
