### ISSUE TITLE
Declare ExtensionObject array variable

### ISSUE THREAD

**Issue by nakr94** [FreeOpcUa/opcua-asyncio#1172]
Hello,
i recently worked with ExtensionObject arrays but i encountered a problem i am unable so solve.
I followed the [example ](https://github.com/FreeOpcUa/opcua-asyncio/blob/master/examples/server-custom-structures-and-enums.py) and modified it to a certain extend. In the following. i will only show parts of the program that are very specific or differ from the example. I can not provide the entirety of the code because of privacy issues.

Besides setting up the server just like the example i generated the new type RobotDataEntry:
<img width="347" alt="issue_01" src="https://user-images.githubusercontent.com/120554349/211810996-2150fead-1f06-4952-8e0c-9f03f37503dc.PNG">

Next i created a variable with this type:
<img width="483" alt="issue_02" src="https://user-images.githubusercontent.com/120554349/211811365-e49347b3-1b4d-455f-ba94-d381f433146d.PNG">
where `N_REQUEST_FIELDS` is a constant set to 100. The `node_id` variable is just a string.

Writing is done with this code:
<img width="568" alt="issue_03" src="https://user-images.githubusercontent.com/120554349/211811668-8966e9f4-5b0a-4b10-972d-00a21687affb.PNG">
<img width="651" alt="issue_04" src="https://user-images.githubusercontent.com/120554349/211811678-c07c4ad6-6342-474b-aab6-1f2f201cb0a0.PNG">

with `construct_opcua_array()` being a method for creating a list of `ua.RobotDataEntry` entries. The self references are due to the class containing this method but basically it is just the same code for initializing the default value on creating the variable.
The variant for example is still `ua.ExtensionObject`.

My question now is: Is this the proper way of defining and updating ExtensionObject arrays? Because clients connecting to the server holding this variable are only receiving an empty array with a size of 100. These clients are written in node-opcua.
I encountered a similar problem described in [this issue](https://github.com/mikakaraila/node-red-contrib-opcua), maybe it is related because the error on the receiving client is the same saying "Internal Error: we are not expecting this dataType to be processed already".
[Here](https://github.com/node-opcua/node-opcua/blob/master/packages/node-opcua-client-dynamic-extension-object/source/resolve_dynamic_extension_object.ts) is a reference to the related code section in line 47.

If you need any further information or code segments, let me know.
Thanks

**Comment by schroeder-** [comment]
Did you try to read the value with UAExpert? This should be the first step, If you UAExpert can read this, your code should be correct.

Also can the client read a scalar value with your datatype? Maybe the client can't read datatype description. You could try the pre 1.04 structs see the example: https://github.com/FreeOpcUa/opcua-asyncio/blob/master/examples/server-custom-structures-before-1.04.py

**Comment by nakr94** [comment]
I tried browsing this server with the FreeOpcua client and it worked as intended. I tried to rollback to the pre 1.04 delcaration but it did not work as well. Even the FreeOpcua client has an issue showing the values of the structure fields when i used the declaration pre 1.04.

**Comment by schroeder-** [comment]
I tried this code and it works with UAExpert:

```Python
   await new_struct(server, idx, "TestStruct", [
        new_struct_field("MyBool", ua.VariantType.Boolean),
        new_struct_field("MyUInt32", ua.VariantType.UInt32),
    ])
    await server.load_data_type_definitions()
    v = [ua.TestStruct(True, 1), ua.TestStruct(False, 2), ua.TestStruct(False, 3)]
    var = await server.nodes.objects.add_variable(idx, "array_node", ua.Variant(v, ua.VariantType.ExtensionObject))
    await var.write_value_rank(1)
    await var.write_array_dimensions([3])
    await var.set_writable()
    async with server:
        while True:
            await asyncio.sleep(1)
```

**Comment by nakr94** [comment]
Is there any limitations on the size of the array?

**Comment by nakr94** [comment]
And maybe another question: Is it possible to store JSON data directly in OPC UA?

**Comment by schroeder-** [comment]
There is a limit for networkmessages, this depends on the client/server if your structure excesses 10 MB you should consider making each value a independent node.

If you want to store JSON you can just store it as String.

**Comment by nakr94** [comment]
Is there no native support for JSON? If i write the message as string, i have to parse it on the receiving end.

**Comment by schroeder-** [comment]
Yes. I theory ExtensionObjects can be encoded/decoded as Json but we don't support that and most other OPC UA implementations. Also you still have to express your JSON content as OPC UA Structure.

**Comment by nakr94** [comment]
ok thank you, i think this is related to node opcua. I will create a related issue in their issue section.
