### ISSUE TITLE
Data type for object nodes

### ISSUE THREAD

**Issue by rwang0417** [FreeOpcUa/opcua-asyncio#1175]
Greetings!

Is it possible to read the data type of object nodes? I am trying to find all the nodes with the type 'PID_Enhanced'. I have some tags(UDT) with this type, but as they are UDTs, they have member variables. When I browse the nodes using opc ua, These PIDE nodes are object nodes so they do not have the data type attribute. I was wondering if the type 'PID_Enhanced' can be read from PLC? If so, how can I read it?

Here is what I see from the PLC code. My target is to get the data type PID_Enhanced using opc ua.
![image](https://user-images.githubusercontent.com/23703553/211942934-0ebf0dd4-8e07-4a9a-9564-e7f38c1a7873.png)

Thanks in advance!

**Comment by schroeder-** [comment]
Sry I miss read you want the type description of a node. 

``` Python
nid = await node.read_type_definition()  # NodeId of the type 
# get the name display name of the NodeId
dt_node = client.get_node(self, nid)
name = await dt_node.read_display_name()
```

**Comment by rwang0417** [comment]
Hi @schroeder, thank you so much for your help! I didn't know I can treat the type as a node as well. 

Unfortunately, it turns out that all the UDTs with different data types in PLC have the same type node as shown below. For example, the UDT with data type PID_ENHANCED and another UDT with data type Timer have the same NodeId 61 and the same display name FolderType.
![image](https://user-images.githubusercontent.com/23703553/212123509-b6ecd26f-12a2-48f5-8693-417a3326e6f4.png)

I checked the Types folder in the Address Space using UAExpert, I couldn't find the PID_ENHANCED type here. Actually none of the UDT data types in PLC can be found here. Does this mean that my OPC UA server (FactoryTalk Linx) does not get the UDT types and there is no way to read it from the client?
![image](https://user-images.githubusercontent.com/23703553/212125561-3d15a814-c06c-4dd3-bd22-aad8183512f7.png)

My settings: PLC(CompactLogix) -> OPCUA server(FactoryTalk Linx) -> OPCUA client(asyncua/UAExpert).

**Comment by rwang0417** [comment]
Hi @schroeder, I think I know what I missed. I need to enable the tag list access in the FactoryTalk Linx Gateway Configuration server configuration and add the tags including UDTs in the tag group.
![image](https://user-images.githubusercontent.com/23703553/212188207-f06169cc-0824-4e13-be35-ddccfb14d623.png)

Now both of the code snippets you shared above work. The difference is that the first one shows PID_ENHANCEDDataType while the second one shows PID_ENHANCEDVariableType. Both can achieve my target. Many many thanks for the great help and for the awesome library!
