### ISSUE TITLE
Server running

### ISSUE THREAD

**Issue by lortolan79** [FreeOpcUa/opcua-asyncio#1191]
Hello,

I need to check if server is currently running. In the past I used "InternalServer.is_running()" method (python_opcua library).
Now I want to migrate to asyncua lib but this method seems not existing anymore.
How can I perform this function?
Thanks in advance.

**Comment by AndreasHeine** [comment]
maybe you can check if on of the servers tasks is still not 
if ServerTask.done() is True: ...

maybe InternalServer.time_task !?
or BinaryServer.cleanup_task -> if it is done the server is down!?
