### ISSUE TITLE
Type hints

### ISSUE THREAD

**Issue by cbergmiller** [FreeOpcUa/opcua-asyncio#12]
I would like to propose the usage of type hints [https://www.python.org/dev/peps/pep-0484/](https://www.python.org/dev/peps/pep-0484/) (at least for the complex types).

For example:
```python
    def publish_callback(self, publishresult: ua.PublishResult):
        self.logger.info("Publish callback called with result: %s", publishresult)
        if self.subscription_id is None:
            self.subscription_id = publishresult.SubscriptionId
```
This could make it easier to understand the code and to enable static type checking (with some IDEs).
It should work fine with python 3.5 and above.
Are there any reservations against the usage of type hints in this project?

**Comment by oroulet** [comment]
No problem with it. I use it in a few projects. But complete typing makes code hard to read... It is too verbose
