### ISSUE TITLE
Adding Nodes from Client on Server. 

### ISSUE THREAD

**Issue by Golem28** [FreeOpcUa/opcua-asyncio#1208]
Is it possible to add nodes on the server from the client. Is there something like a node service for this?

**Comment by schroeder-** [comment]
It is possible, if the sever allows that. Most don't allow it. 

The client and server code work the same way. So you can look at the server examples how to create nodes.

**Comment by AndreasHeine** [comment]
Please use the https://github.com/FreeOpcUa/opcua-asyncio/discussions for questions!
