### ISSUE TITLE
Best way to Write to Multiple Nodes at once?

### ISSUE THREAD

**Issue by TheWicklowWolf** [FreeOpcUa/opcua-asyncio#1210]
I'm using the Client from asyncua.sync.
When reading multiple values, read_values(nodes) works well. What is the equivalent for writing multiple values?

**Comment by AndreasHeine** [comment]
https://github.com/FreeOpcUa/opcua-asyncio/discussions/1199

please use the [discossions](https://github.com/FreeOpcUa/opcua-asyncio/discussions) for questions
