### ISSUE TITLE
AttributeError: 'Node' object has no attribute 'read_value'

### ISSUE THREAD

**Issue by Elthas17** [FreeOpcUa/opcua-asyncio#123]
Dear,

Thanks for opcua-asyncio

In your examples you comment out a line such as:
https://github.com/FreeOpcUa/opcua-asyncio/blob/master/examples/client-example.py

Line 46 #var.read_value() # get value of node as a python builtin 

When connected to an OPC UA server (Beckhoff CX8091) this fuction yields:

> print(var.read_value()) # get value of node as a python builtin
> AttributeError: 'Node' object has no attribute 'read_value'
> INFO:asyncua.client.ua_client.UASocketProtocol:Socket has closed connection

 var.get_value() yields the expected result instead

My code snippit
```
var = client.get_node(ua.NodeId('MAIN.mynode', 4)) 
print(var.read_value()) # gives an error
print(await var.get_value()) # works fine
```

**Comment by oroulet** [comment]
Get_value just got renamed to read_value. Run asyncua from master if you want read_value

**Comment by Elthas17** [comment]
I installed the latest version with pip, so pip does not hold the latest version of the master branch?

**Comment by oroulet** [comment]
No. Pip has released versions.

**Comment by tukotech** [comment]
Just installed 0.8.4 using pip, <node>.read_value() works. Should this issue be closed?

**Comment by swamper123** [comment]
Since there are no complains since months and the renaming was clarified, the Case seems to be closeable 🕵️
