### ISSUE TITLE
await server.load_data_type_definitions() does not parse Structure imported from xml

### ISSUE THREAD

**Issue by vhavard** [FreeOpcUa/opcua-asyncio#1234]
**Describe the bug** <br />
Create an xml file to define a OPCUA model 
importer the xml into the server
use the server.load_data_type_definition() to get the class of the object
````python
logging.basicConfig(level=self.ufp_config["logging_level"], force=True)
server = Server()
await server.init()
uri = "http://server.fr/test"
server.set_endpoint("opc.tcp://0.0.0.0:4840/server/")
server.set_server_name("TEST import_xml and load_data_type_definition")
idx = await server.register_namespace(uri)

model_import = await server.import_xml("path/to/model.xml")
ctypes = await server.load_data_type_definitions() # bug line
# return {}, should return the DataType declared in the xml
````
**To Reproduce**<br />
use the code above

**Expected behavior**<br />
should return the dictionary containing each DataType declared in the xml, but return empty dictionary instead

**Version**<br />
Python-Version: 3.9.15 <br />
opcua-asyncio Version 1.0.1

**Comment by schroeder-** [comment]
No bug, import_xml already generated the datatypes. So the second call doesn't yield any datatypes.

**Comment by vhavard** [comment]
Thank you, I found the solution to access my personnal datatype
````python
ua.__dict__["QuaternionDataType"](1, 5, 8, 1)
QuaternionDataType(x=1, y=5, z=8, w=1)
````
I leave the answer to help people

**Comment by vhavard** [comment]
> No bug, import_xml already generated the datatypes. So the second call doesn't yield any datatypes.

By the way, is there another mean to get the classes generated via the import_xml() method ?

For the moment, I am using this:
```python
ua.__dict__["QuaternionDataType"](1, 5, 8, 1)
# return QuaternionDataType(x=1, y=5, z=8, w=1)
```

**Comment by schroeder-** [comment]
can also do this:
ua.QuaternionDataType(x=1, y=5, z=8, w=1)
ua.QuaternionDataType(1, 5, 8, 1)
