### ISSUE TITLE
Cannot create alias for node.

### ISSUE THREAD

**Issue by Flock1993** [FreeOpcUa/opcua-asyncio#1264]
I'm trying to create alias for node.
With using of examples.client-minimal.py i make my local OPC UA server with one variable - MyVariable.
Variable in UaExpert
![image](https://user-images.githubusercontent.com/86944512/227904240-d982c689-e8a6-4ddd-b356-b00e665c9f2f.png)
I set alias to MyVariable by this code:
```
async with Client(url="opc.tcp://admin@localhost:4840/freeopcua/server/") as client:
    var = await client.nodes.root.get_child(
        ["0:Objects", f"2:MyObject", f"2:MyVariable"]
    )
    alias = ua.LocalizedText("MB0")
    await var.write_attribute(ua.AttributeIds.DisplayName, ua.DataValue(alias))
```
After setting alias "MB0" i connect to server by UaExpert.
When i use Root -> Objects -> Aliases -> FindAlias call with "MB0"
![image](https://user-images.githubusercontent.com/86944512/227904454-a17bc948-d4e6-4f59-9686-675e818e5021.png)
There is a error: "BadNothingToDo".
And this tells me that I created the alias incorrectly.
What i am doing wrong and how can i fix alias setting?

**Comment by schroeder-** [comment]
You have to implement the function "FindAlias" your self. Use link_method todo this.

**Comment by AndreasHeine** [comment]
you should read this before:
https://reference.opcfoundation.org/Core/Part17/v104/docs/

**Comment by Flock1993** [comment]
Closing the issue, it was not OPC UA, but OPC DA with fake UA shell.
