### ISSUE TITLE
Change a single value of NodeId's within a loop

### ISSUE THREAD

**Issue by Newinthistopic** [FreeOpcUa/opcua-asyncio#1268]
Hello dear people,

I have a variable here that is declared inside a loop.
Now I want to change single values in the Get function.
The loop goes from 0 to 14. I want to change NodeId 4.

Can anyone help me, I would be very grateful for help.

Here is my code:

var WarningH = namespace3.addVariable({
                componentOf: nr,
                browseName: "WarningH",
                dataType: opcua.DataType.Float,
                nodeId: "ns=3;s=" + "\"ZEEX_3111_Parameter\".\"udtEmPz\"" + "[" + i + "]" + ".\"rTempH\".\"Set\"",
                value: {
                    get: function () {
                        var WarningHNodeId = this.nodeId.value;

                   

                        return new opcua.Variant({ dataType: opcua.DataType.Float, value: serverValues[WarningHNodeId] });
                    },
                    set: function (variant) {

                        const WarningHNodeId = this.nodeId.value;
                        serverValues[WarningHNodeId] = parseFloat(variant.value);

                        console.log(`Setter-Funktion aufgerufen für WarningH mit nodeId "${WarningHNodeId}": ${serverValues[WarningHNodeId]}`);
                        console.log(`------------------------------------`);

                        const neueNodeId = WarningHNodeId.replace("Set", "Min");
                        //Replace Funktion wurde hier zwei mal angewendet, zuerst Set durch min tauschen und dann rTempTolH auf rTempTolHH
                        const AlarmHHMinNodeId = neueNodeId.replace("rTempH", "rTempHH");
                        serverValues[AlarmHHMinNodeId] = serverValues[WarningHNodeId]
                        console.log(`AlarmHHMin nodeId:${AlarmHHMinNodeId}\nAlarmHHMin Wert: ${serverValues[AlarmHHMinNodeId]}\n`);

                        // serverValues[rActNodeId] = serverValues[rSetNodeId];

                        return opcua.StatusCodes.Good;

                    }
                }
            })

**Comment by AndreasHeine** [comment]
wrong repo!
