### ISSUE TITLE
How to get type of subscribed node?

### ISSUE THREAD

**Issue by unregistered33** [FreeOpcUa/opcua-asyncio#1286]
Hello!  Not issue, just question.
How to get the value ua type in  `datachange_notification(self, node: Node, val, data)` (int, float, bool etc)? I need to sort the monitored items received depending on their ua type
Thanks a lot!

**Comment by schroeder-** [comment]
There are multiple ways. 
Either you read the datatype before hand and provide it in your SubscriptionHandlerInstance.

You can check the variant type in the `datachange_notification`.
``` python
var: ua.Variant = data.subscription_data.Value.Value 
type: ua.VariantType = var.VariantType
```

You can use the python way: 
``` Python
t = type(val)
if t == str:
    ....
elif t == bool:
   ....
```

**Comment by unregistered33** [comment]
Thanks, Alexander!

**Comment by unregistered33** [comment]
a small clarification
var: ua.Variant = data.subscription_data.Value.Value 
need var: ua.Variant = data.**monitored_item**.Value.Value
