### ISSUE TITLE
Rename namespace opcua. It must be possible to install both sync and asynchronous versions..

### ISSUE THREAD

**Issue by oroulet** [FreeOpcUa/opcua-asyncio#13]
This is going to be a lot of renaming...

**Comment by oroulet** [comment]
@cbergmiller I propose asyncua or aioua as the new python module name. speak up soon if you have a better idea. I want to rename this asap.
aioua maybe respect more the naming of all aio-libs  https://github.com/aio-libs?page=2  but I thing asyncua is easier to read...

asyncua
async-ua
aioua
aio-ua

**Comment by cbergmiller** [comment]
I like aoiua even though it's hard to pronounce.

**Comment by oroulet** [comment]
I tend to prefer asyncua. It very close to asyncio and opcua

**Comment by cbergmiller** [comment]
So let's settle on asyncua
