### ISSUE TITLE
Get Tree of objects

### ISSUE THREAD

**Issue by luisfmelo** [FreeOpcUa/opcua-asyncio#133]
Hi,

first of all, thanks for the library. It seems really good in my first days studying it. 

I have one question. Is it possible to retrieve the tree of objects of a server? 
Without getting children recursively, of course.

**Comment by oroulet** [comment]
You never went to get the entire tree it is too big. But using get_children () you can easily navigate tree

**Comment by oroulet** [comment]
You can also export nodes to xml

**Comment by swamper123** [comment]
Maybe you can grab the nodes of a namespace you want via get_nodes_of_namespace, maybe filter it and then use the exporter.built_etree() method to get a tree.
Or export them in an xml file and try to find your ways through the structure.

**Comment by swamper123** [comment]
Seems to be solved by inactivity. Case closed 🕵️
