### ISSUE TITLE
How can I write value to the specific index of the array

### ISSUE THREAD

**Issue by TomasRychy** [FreeOpcUa/opcua-asyncio#1338]
Hello,

I need write a value to the multi-dimensional array to specific index.
I know how to overwrite whole array with this specific value inside of the new value of the array, but I don't know how to write the value to the specific index without overwriting of whole array.
Can you tell me how I can do that?

Thank you,
Tomas

**Comment by TomasRychy** [comment]
P.S.: I've tried this, but it returns code BadIndexRangeNoData.
await var.write_attribute(ua.AttributeIds.Value, ua.DataValue(ua.Variant(new_value, ua.VariantType.Int16, is_array=True)), "1")

**Comment by TomasRychy** [comment]
My other question is, if it is possible set values like subrange of array.

**Comment by schroeder-** [comment]
On thing is if the opc ua server support index ranges. Not all do. 
Did you try to change a single value via uaexpert? But I am not sure if ua expert is just sending the updatet array.

**Comment by TomasRychy** [comment]
I try it on OPC UA server which should be able to change some subrange if the array. My problem is that I don't know how to do it in Python. Can you help me with that?

**Comment by TomasRychy** [comment]
UAExpert supports only writing to one specific array index. I need to write values to subrange of array.

**Comment by schroeder-** [comment]
I never used it, but this is how it should work:

Write value 10 -> 20

```
new_value = [i+100 for i in range(9)]
await v_ro.write_attribute(ua.AttributeIds.Value, ua.DataValue(ua.Variant(new_value, ua.VariantType.Int16, is_array=True)), '10:20')
```
write a single value at pos 30
```

new_value = [1]
await v_ro.write_attribute(ua.AttributeIds.Value, ua.DataValue(ua.Variant(new_value, ua.VariantType.Int16, is_array=True)), '30')
```

**Comment by schroeder-** [comment]
This is how the string should be formated from the spec: 
[Spec](https://reference.opcfoundation.org/Core/Part4/v104/docs/7.22)

**Comment by TomasRychy** [comment]
Thank you! It looks like it works. Can you please help how can I do it for 2D array? It returns to me error BadIndexRangeNoData. But maybe it is the bug on the side of the server. I'm investigating it.

new_value = [2]
await var.write_attribute(ua.AttributeIds.Value, ua.DataValue(ua.Variant(new_value, ua.VariantType.Int16, is_array=True)), '0,0')

**Comment by schroeder-** [comment]
```
new_value = [2]
await var.write_attribute(ua.AttributeIds.Value, ua.DataValue(ua.Variant(new_value, ua.VariantType.Int16, is_array=True)), '0')
```

**Comment by TomasRychy** [comment]
No it works. My code looks like this:

`new_value = [[0, 0], [0, 0]]
            await var.write_attribute(ua.AttributeIds.Value, ua.DataValue(ua.Variant(new_value, ua.VariantType.Int16, is_array=True)), '1:2,1:2')`

You can close the issue :)

**Comment by TomasRychy** [comment]
Thank you for your support :)
