### ISSUE TITLE
Problem reading arrays inside an ExtensionObject variable

### ISSUE THREAD

**Issue by ThomasDegallaix** [FreeOpcUa/opcua-asyncio#1388]
First of all, thank you very much for your hard work !

We are trying to send data from an OPCUA server embedded in a PLC using Codesys to an embedded computer acting as a client. Sending data generally works fine, except when we decide to send more complex data containing arrays, which take the form of structures in Codesys and are translated into ExtensionObjects when using the OPCUA protocol.

When we check the contents of the variables using the UAExpert client, the arrays are complete and can be read without any problems. However, when these same variables are retrieved by the OPCUA asyncio client on the embedded computer, the arrays are no longer treated as such and data is lost. We retrieve the data by subscribing to the nodes and storing them in a queue once they have been received in the callback notifying us of data modifications.

A test was carried out with 2 ExtensionObjects with arrays of 10 Int16 containing different data. 
![image](https://github.com/FreeOpcUa/opcua-asyncio/assets/32198669/672368dd-8b86-430d-adbd-779de673c2a8)
![image (1)](https://github.com/FreeOpcUa/opcua-asyncio/assets/32198669/ff1beb90-b134-46a8-86b7-7d783deeed9b)

Here are the results when reading the variables using the UAexpert client :

![Screenshot from 2023-08-03 11-57-45](https://github.com/FreeOpcUa/opcua-asyncio/assets/32198669/03dda3cd-22dc-4c36-944c-20860e6dc6e4)

![Screenshot from 2023-08-03 11-58-50](https://github.com/FreeOpcUa/opcua-asyncio/assets/32198669/692f6ff9-11e4-4c9a-a272-0a2d605a220f)

And here are the results when reading the variables using the library :

![Screenshot from 2023-08-03 11-52-10](https://github.com/FreeOpcUa/opcua-asyncio/assets/32198669/2ec6bef1-5c81-4ee3-b1e2-1fa5240cdb1a)

![Screenshot from 2023-08-03 11-51-48](https://github.com/FreeOpcUa/opcua-asyncio/assets/32198669/904e7e45-9284-435d-81b2-3454ad5aaadc)

After displaying the contents, it can be seen that the size of the 1st array is correctly read, but the contents are limited to the value of the data at the beginning of the list. Then, the size of the next list corresponds to the addition of the 4 bytes of the next 2 indexes (concatenating the binary of 2 and 3 gives 196610 in Int32 decimal writing, and the same applies to the second list with 12 and 13, which gives 851980 in Int32). Finally, the contents of the 2nd list correspond to the contents of the 4th value of the 1st list. The data is therefore decoded as a succession of bytes, irrespective of the fact that they are lists.

Interestingly, if I call the read_value() function directly on the ExtensionObject field containing the array, the data is correctly decoded.

We are currently running python 3.8.10 and opcua asyncio 1.0.3

Thanks in advance !

**Comment by schroeder-** [comment]
Did you call load_type_definitions or load_data_type_definitions to load the datatypes?

**Comment by ThomasDegallaix** [comment]
Yes, I tried both. Only load_type_definitions() allows me to decode correctly most of the data except arrays embedded inside an ExtensionObject.

**Comment by schroeder-** [comment]
Then the server doesn't support the new DataType definitions. 
load_type_definitions is not complete, maybe you can extract the bsd of the datatype? 
This is done if go under Root -> Types -> DataTypes -> OPC Binary , there you can extract the value of the top level nodes (Dictonarys), as binary string?

**Comment by ThomasDegallaix** [comment]
Thank you for the advice !
When I reach OPC Binary, I can see all our ExtensionObjects. 
![image](https://github.com/FreeOpcUa/opcua-asyncio/assets/32198669/e84a7bb0-8887-4045-b60c-3f72cd79415b)

However when I select the datatype used during our test and check the attributes and specifically the field value, it only gives me datatype.
![image](https://github.com/FreeOpcUa/opcua-asyncio/assets/32198669/0eae026a-2856-4379-a8ca-d7dffaaabb6f)

Is there any other way to get the bsd ?

**Comment by schroeder-** [comment]
The bsd is in the top level variable "CODESYSSPV3/S3/LecVarAccess"

**Comment by ThomasDegallaix** [comment]
After converting the hex value of the bsd to a readable format I got this :
```
<opc:StructuredType BaseType='ua:ExtensionObject' Name='ecomat_display.StructTest2'>
<opc:Field TypeName='opc:Int16' Name='var1'/>
<opc:Field TypeName='opc:Int16' Name='var2'/>
<opc:Field TypeName='opc:Int32' Name='__test_list1Length'/>
<opc:Field TypeName='opc:Int16' LengthField='__test_list1Length' Name='test_list1'/>
<opc:Field TypeName='opc:Int32' Name='__test_list2Length'/>
<opc:Field TypeName='opc:Int16' LengthField='__test_list2Length' Name='test_list2'/>

</opc:StructuredType><opc:StructuredType BaseType='ua:ExtensionObject' Name='ecomat_display.StructTest1'>
<opc:Field TypeName='opc:Int16' Name='var1'/>
<opc:Field TypeName='opc:Int16' Name='var2'/>
<opc:Field TypeName='opc:Int32' Name='__test_list1Length'/>
<opc:Field TypeName='opc:Int16' LengthField='__test_list1Length' Name='test_list1'/>
<opc:Field TypeName='opc:Int32' Name='__test_list2Length'/>
<opc:Field TypeName='opc:Int16' LengthField='__test_list2Length' Name='test_list2'/>
```
I'm not sure about what should be printed in case of fields containing arrays but it seems to follow the original format.

**Comment by schroeder-** [comment]
Ok our passer doesn't support that syntax currently. A Length Field has to have to start with "NoOf", instead of end with "Length".

**Comment by ThomasDegallaix** [comment]
Thank you very much for your explanation !
Do you think there is anything I could do to make it work ? However, I don't think there is anything I can do on the Codesys side.

**Comment by schroeder-** [comment]
I don't think you can change anything on the codesys side. But I can make a pr, soon. It is only a smal change.

**Comment by ThomasDegallaix** [comment]
Thank you for your involvement,  I can't wait to see the modification. It will be really useful for us !

**Comment by schroeder-** [comment]
Made a pr #1395 let me know if it works for you.

**Comment by ThomasDegallaix** [comment]
It works like a charm, thank you !
