### ISSUE TITLE
Use dataclasses to remove code

### ISSUE THREAD

**Issue by oroulet** [FreeOpcUa/opcua-asyncio#14]

**Comment by oroulet** [comment]
If interesting....

**Comment by cbergmiller** [comment]
Do you mean for the auto-generated ua classes?

**Comment by oroulet** [comment]
Yes. But it might not be a perfect fit....

**Comment by swamper123** [comment]
@oroulet I guess this old one is more or less done/still in progress?

**Comment by oroulet** [comment]
Done
