### ISSUE TITLE
It seems that load_data_type_definitions loads only the base UA Data Types under Structure, but not the additionally loaded Data Types from other nodesets.

### ISSUE THREAD

**Issue by plamenk** [FreeOpcUa/opcua-asyncio#1475]
Hi, I have a question re. this issue: I use link_method to implement a method in the server. It seems that load_data_type_definitions loads only the base UA Data Types under Structure, but not the additionally loaded Data Types from other nodesets. 
How can I use Data Types from imported xml nodesets, for example to create an output within my implemented method in the form:

...
    value = ua.uaprotocol_auto.F_JobResponseDataType()
    value.JobOrderID = input.Value
...

May data type, generated by SiOME under Types/DataTypes/BaseDataType/Structure is here:

    <UADataType NodeId="ns=10;i=3005" BrowseName="10:F_JobResponseDataType">
        <DisplayName>F_JobResponseDataType</DisplayName>
        <References>
            <Reference ReferenceType="HasSubtype" IsForward="false">i=22</Reference>
            <Reference ReferenceType="HasEncoding">ns=10;i=5092</Reference>
            <Reference ReferenceType="HasEncoding">ns=10;i=5093</Reference>
        </References>
        <Definition Name="F_JobResponseDataType">
            <Field DataType="String" Name="JobOrderID"/>
            <Field IsOptional="true" DataType="String" Name="Description"/>
            <Field IsOptional="true" DataType="String" Name="ProductID"/>
            <Field IsOptional="true" DataType="String" Name="PartSerialNumber"/>
            <Field IsOptional="true" DataType="DateTime" Name="StartTime"/>
            <Field IsOptional="true" DataType="DateTime" Name="EndTime"/>
            <Field DataType="ISA95JobOrderStateEnum" Name="JobState"/>
            <Field IsOptional="true" DataType="ns=10;i=3013" Name="PartState"/>
            <Field IsOptional="true" DataType="Int32" Name="LinePosition"/>
            <Field IsOptional="true" DataType="String" Name="MaterialContainerIDIn"/>
            <Field IsOptional="true" DataType="String" Name="MaterialContainerIDOut"/>
            <Field IsOptional="true" DataType="ns=10;i=3012" Name="JobResponseData"/>
            <Field IsOptional="true" DataType="ns=10;i=3017" ValueRank="1" Name="PersonnelActuals"/>
            <Field IsOptional="true" DataType="ns=10;i=3015" ValueRank="1" Name="EquipmentActuals"/>
            <Field IsOptional="true" DataType="ns=10;i=3018" ValueRank="1" Name="PhysicalAssetActuals"/>
            <Field IsOptional="true" DataType="ns=10;i=3001" ValueRank="1" Name="MaterialActuals"/>
        </Definition>
    </UADataType>

Thanks.

Plamen

PS: I am afraid that I commented a closed issue or discussion, so I created her a new one. 

_Originally posted by @plamenk in https://github.com/FreeOpcUa/opcua-asyncio/discussions/1293#discussioncomment-7373942_

**Comment by schroeder-** [comment]
You use the wrong module.
This should work. 

`ua.F_JobResponseDataType()`

**Comment by plamenk** [comment]
So easy!. Great thanks, Alex, for the prompt response.

**Comment by plamenk** [comment]
thanks!
