### ISSUE TITLE
I am using client.get_attributes() method for the bulk read of the nodes, in which the response containes value, sourcetimestamp, servertimestamp and status code. How can i get node id also in the response.

### ISSUE THREAD

**Issue by KuroAshi75** [FreeOpcUa/opcua-asyncio#1514]
I have tried to change the AttributeId's argument, but then 'nodeid' is overwriting 'value' in response.
![image](https://github.com/FreeOpcUa/opcua-asyncio/assets/95868857/99facb08-85ea-4c9f-8628-46e1c9dd70f6)

**Comment by schroeder-** [comment]
```
nodes = [client.get_node('ns=4;i=4'), ...]
res = client.read_attributes(nodes, ....)
for node, value in zip(nodes, res):
     ....
```

**Comment by KuroAshi75** [comment]
Hi Alex, just a small query, what is the limit to the count of nodes I can query at a time?

**Comment by schroeder-** [comment]
There can be limits, see https://reference.opcfoundation.org/Core/Part5/v104/docs/6.3.11, but not all servers expose that value. I would make the max query value configurable and limit it to 10000 per request.
