### ISSUE TITLE
get_children() memory leak or runaway behaviour in asyncua 1.0.5 

### ISSUE THREAD

**Issue by magnetohack** [FreeOpcUa/opcua-asyncio#1519]
**Describe the bug** <br />
get_children() appears to have a memory leak or runaway behaviour for asyncua version 1.0.5 that was not present in version 1.0.4.

**To Reproduce**<br />
Steps to reproduce the behavior incl code:

Example code for traversing down to the relevant data nodes. Last call to get_children() fails.
<pre>
# Connect and traverse tree to locate top node for sensor data
client = Client(url)
await client.connect()

# Get a list of all 'sensor data' nodes
root = client.get_root_node()
children = await root.get_children()
c85 = await children[0].get_children()
c851 = await c85[1].get_children()
allsensors = await c851[2].get_children()
</pre>

The last get_children() call should return about 83000 items. Using asyncua version 1.0.4 this works fine, while in version 1.0.5 it consumes all available memory before failing.

**Expected behavior**<br />
Expect the get_children() call to return list of child nodes without crashing or consuming all memory.

**Version**<br />
Python-Version: Tested on 3.9 and 3.11. Problem in both cases<br />
opcua-asyncio Version 1.0.5 (current default with pip install)

**Comment by oroulet** [comment]
rather strange, I do not see any other changes than typing in node.py and client code since 1.0.4...

**Comment by oroulet** [comment]
@magnetohack I went again through all commits but I really cannot find any code that can be related to that behaviour. Do you know how to use git bisect? it would be great if you could run that between 1.0.4 and and master to find out where that behaviour has changed

**Comment by joshbode** [comment]
I am also seeing this issue for 1.0.5, i.e. getting children and rapidly consuming all available memory - I will try to see what might be causing it.
1.0.4 does not appear to have this issue.

**Comment by joshbode** [comment]
it's something in daa74c2.
0cd54642 doesn't have the issue.

**Comment by joshbode** [comment]
looks like the line:
```
        while head.ContinuationPoint:
```
is possibly the problem - `head` doesn't get updated in the loop

**Comment by schroeder-** [comment]
Your change is correct. I would add the None check. Would be nice if you could make a pr with this changes.

**Comment by oroulet** [comment]
we got it by the classical "Hide code change into a typing or formatting commit". I should really be more hard on these things

**Comment by oroulet** [comment]
also it even added an assert in runtime code. https://github.com/FreeOpcUa/opcua-asyncio/commit/daa74c28033e765d2d56d6a81a995ba246818658#diff-e055ac7ac1261dd441f9e8dd2f6bea3d44c5ab602d7ec250e93c70ff4873b52dR59 That should never be done @okapies . We should not crash because a server behaves badly. please  return some UaError

**Comment by schroeder-** [comment]
It adds multiple asserts in places where a exception should be thrown.

**Comment by okapies** [comment]
Pushed #1533. Could you check it?

**Comment by oroulet** [comment]
@okapies thank you for your quick reaction. Looks good now I think

**Comment by oroulet** [comment]
looks like that one god flagged as competed automatically.  @joshbode does it work for you? is so we let it closed

**Comment by oroulet** [comment]
@okapies you still have one assert in your RelativePathFormater code. Can you fix it?
Btw I do not know if you saw it but now I made your code the default for any path in examples in a recent commit. Luckily for me (and other users), the strange historical way to specify path was compatible with the relative path from spec. Good work on that!

**Comment by okapies** [comment]
Thanks for the catch. Fixed in #1535.
