### ISSUE TITLE
DataTypeEncoding object pointed by the "HasEncoding" links should have node class Object instead of ObjectType 

### ISSUE THREAD

**Issue by erossignon** [FreeOpcUa/opcua-asyncio#1549]
**Describe the bug** <br />

Found while investigating [node-opcua/issue1232](https://github.com/node-opcua/node-opcua/issues/1232)

https://github.com/FreeOpcUa/opcua-asyncio/blob/f48b4f51fda55b67d3106ff6800e868c4e060fec/asyncua/common/manage_nodes.py#L401

should be  Object and not ObjecType

**To Reproduce**<br />
Use [example.py](https://raw.githubusercontent.com/FreeOpcUa/opcua-asyncio/master/examples/server-custom-structures-and-enums.py)

**Expected behavior**<br />

**Screenshots**<br />
actual
![image](https://github.com/FreeOpcUa/opcua-asyncio/assets/680220/9a76dc2f-73f5-48f1-be93-541690ee45cf)
The DataTypeEncoding instance is wrongly set to  nodeClass=ObjectType
![image](https://github.com/FreeOpcUa/opcua-asyncio/assets/680220/50ece10f-9250-4a5c-80d0-9f862ef997cb)

Expected  ( like in any other companion specification )
The DataTypeEncoding instance should be nodeClass=Object
 
![image](https://github.com/FreeOpcUa/opcua-asyncio/assets/680220/5b36c10f-bd31-4035-9022-c0b5a6c208ba)

**Version**<br />
Python-Version:  3.x
opcua-asyncio: 1.0.6

**Comment by rempAut** [comment]
Looks like also fixes #1524
