### ISSUE TITLE
How can I know if the connection is still active?

### ISSUE THREAD

**Issue by luisfmelo** [FreeOpcUa/opcua-asyncio#155]
Is there a way to know if the connection is still active?

I tried with `send_hello` but when I send that message, the connection drops after a while. (wondering why)

Is there any way? will make sense to have that functionality?

**Comment by oroulet** [comment]
the safest is to read the attribute value of a node

**Comment by chrisjbremner** [comment]
See https://github.com/FreeOpcUa/python-opcua/pull/971
