### ISSUE TITLE
The following references could not be imported and are probably broken.  

### ISSUE THREAD

**Issue by varunJainV** [FreeOpcUa/opcua-asyncio#1584]
### Could not be imported!

---
 **self.server = Server()
 await self.server.init()
 self.server.set_endpoint(self.endpoint)
 await self.server.import_xml(self.xmlfile)**

In import_xml method I am getting following error: 
**The following references could not be imported and are probably broken.**
![ImportFailure](https://github.com/FreeOpcUa/opcua-asyncio/assets/160575473/2f018b35-dd7a-44fc-a2cc-48d3263baf0b)

**Comment by schroeder-** [comment]
Can you post a complete log, not an incomplete screenshot?

Also can you post the xml file if possible? Otherwise can you post a log with log level Debug?

**Comment by varunJainV** [comment]
Thank You for your response. 
Here  I am sharing the complete screen shot and xml file.
 
![Importfailure1](https://github.com/FreeOpcUa/opcua-asyncio/assets/160575473/0db38852-2991-43d5-ba29-59790bbe17b8)
![importFailure2](https://github.com/FreeOpcUa/opcua-asyncio/assets/160575473/6bd14513-1dfd-4ded-a8f0-53958bf5811c)

Link of the XML file [https://reference.opcfoundation.org/api/nodesets/61](url)

**Comment by schroeder-** [comment]
Do you load the required nodesets before? http://opcfoundation.org/UA/DI/ and http://opcfoundation.org/UA/PlasticsRubber/GeneralTypes/ ?

**Comment by varunJainV** [comment]
Iam using the following to load nodesets:
![image](https://github.com/FreeOpcUa/opcua-asyncio/assets/160575473/ddd3343d-bc8f-4a09-845f-e5df1fc497ad)

**Comment by schroeder-** [comment]
Do you even read my responeses....

**Comment by varunJainV** [comment]
Can you please confirm, How to load them?
