### ISSUE TITLE
Stuck in obtaining the read_data_type() of node. Related to asyncio feature.

### ISSUE THREAD

**Issue by DiogoFran** [FreeOpcUa/opcua-asyncio#1612]
**Describe the bug** <br />
The process of acquiring a read_data_type() of node stayed stuck and i don't know why.
 I don't know if it's my dumb approach.

**To Reproduce**<br />
I have a module python (x.py) that calls the object My_OPCUA_Client, as follow:
![Screenshot 2024-04-09 094118 - Copy (2)](https://github.com/FreeOpcUa/opcua-asyncio/assets/51442304/6957d191-cbaf-4f4a-8050-ed123832d3b4)
My Object My_OPCUA_Client.
![image](https://github.com/FreeOpcUa/opcua-asyncio/assets/51442304/f010e8a1-fd35-45ee-a07b-d6bbc8895324)
After creating the OPCUA client instance i call from x.py the function getNodeId() which is async, as shown above:
![image](https://github.com/FreeOpcUa/opcua-asyncio/assets/51442304/ff66691b-56f1-46d9-b728-fd8561e5f6dd)

After that, the python interpreter stayed stuck. The result that i obtained is:
![image](https://github.com/FreeOpcUa/opcua-asyncio/assets/51442304/c40d66aa-0eed-4a48-909b-e369f0e6c8bc)
So, it starts the awaitable coroutine read_data_type() but doesn't return.

**Expected behavior**<br />
Obtaining the data type of node asynchronously

**Version**<br />
Python-Version:3.11.5
asyncua:1.0.4
asyncio:1.5.8

Thanks for any help.

**Comment by oroulet** [comment]
you need to do a bit more asyncio training. you cannot use asyncio.run that way

**Comment by DiogoFran** [comment]
Hello, could you give me some tip? 
Thank you

**Comment by schroeder-** [comment]
1. First dont post screenshoots, always add code as text. Also log outputs. It's hard to read and understand screenshoots.
2. read about asyncio
3. Here a incomplete example to use asyncio for your code:
Remove asyncio.run(create_client()) from My_OPC_UA_Client __init__

```
async def run_client():
    client = My_OPC_UA_Client():
    await client.create_client()
    await client.get_node_ide("id")

if __name__ == "__main__":
    asyncio.run(run_client())
   
```

**Comment by DiogoFran** [comment]
Sorry for the screenshots. 
I have read about that, the option mentioned only works if i want to run the script as the initial program entry point which doesn't happen.  
I think the flow of my code, finishes the first asyncio.run() (when the object is created) and after goes to the asyncio.run() to execute the async function "getNodeId". I am not understanding the error.

**Comment by oroulet** [comment]
you need to have only one asyncio loop for the entire session (roughly). in a big application the the loop should be running already. Sounds like you in reality want to write sync code. Use the sync wrapper then

**Comment by DinoFra** [comment]
Hello again, i could not find the answer.
I verified if the application already had a loop, but it didn't.   I just want to initialize an object with an already configured client. After that, i want to call the object to pick up nodes when i need it.
What's the wrapping you're talking about?
