### ISSUE TITLE
Issue with Migrating from opcua to asyncua.sync: AttributeError when accessing get_objects_node

### ISSUE THREAD

**Issue by HackersSpirit** [FreeOpcUa/opcua-asyncio#1644]
I am currently migrating a project from the opcua library to asyncua.sync. I've encountered an issue where the method get_objects_node() is not recognized, leading to an AttributeError. Below is a simplified version of the code snippet and the error message I'm encountering:
```
def setup_control__var(self, ns_index):
    """
    This method sets up variables for controlling statuses. It aims to connect the update callback to a named variable in the server.
    """
    obj = super().get_objects_node().add_object(ns_index, "CONTROL_STATUS_OBJECT")

```
Error Message

```
File "/path/to/server_opcua.py", line X, in __init__
    self.setup_control__var(NAMESPACE_INDEX)
File "/path/to/server_opcua.py", line Y, in setup_control__var
    obj = super().get_objects_node().add_object(ns_index, "CONTROL_STATUS_OBJECT")
AttributeError: 'super' object has no attribute 'get_objects_node'
```

Expected Behavior:
The code should access the base "Objects" node of the server and add a new object under this node.

Actual Behavior:
An AttributeError is thrown, indicating that get_objects_node() is not available.

Steps to Reproduce:

Migrate server setup code from opcua to asyncua.sync.
Implement server initialization with a call to setup_control_status_variables.
Run the server initialization process.

Environment:

Python version: 3.10
asyncua version: 1.1.0
Operating System: 23.04

Additional Context:
This functionality worked as expected in the opcua library, but seems to not be directly compatible or requires a different approach in asyncua.sync. Any guidance on how to correctly migrate this functionality would be greatly appreciated.

**Comment by oroulet** [comment]
Client.nodes.objects is the same thing. maybe get_object_node() was removed
