### ISSUE TITLE
How to catch exceptions such as ServiceFault...

### ISSUE THREAD

**Issue by Take44** [FreeOpcUa/opcua-asyncio#170]
When the server side is really stopped by shutdown etc., Please tell me how to catch exceptions such as ServiceFault on the client side.

**Comment by oroulet** [comment]
Try:
   Node.read_value()
Except ua.ServiceFault as ex:
     Whatever

**Comment by Take44** [comment]
Thank you very much.
Certainly there was a way. And easy.
I was in trouble when changing data by subscribing.
I will try and confirm.

**Comment by oroulet** [comment]
You will not get exception when using subscriptions. You need to have another thread(usually main thread) reading some values on server to discover issues
