### ISSUE TITLE
 get_namespace_array is not async

### ISSUE THREAD

**Issue by swamper123** [FreeOpcUa/opcua-asyncio#180]
Hello together,
just found an Issue here:

https://github.com/FreeOpcUa/opcua-asyncio/blob/5132c4edee2ae8348e5d960a2f890341b899d916/asyncua/server/server.py#L419

I guess `get_namespace_array` shall be a `async def` and return the value of the NamespaceArray Node.

**Comment by oroulet** [comment]
yes and there should be a simple test jsut to make sure it does not happen again. Can you send a PR?

**Comment by swamper123** [comment]
I will drop sth. in the next days.

**Comment by swamper123** [comment]
There have been more files missing an async: 

- get_namespace_array (server.py & client.py)
- import_xml (server.py & client.py)
- delete_nodes (server.py & client.py)
- load_type_definitions (server.py & client.py)
- load_enums (server.py & client.py)
- _add_node (xmlimporter.py)
- stop (history.py in Class HistoryManager seems to be a Coroutine)
- history_read (internal_sessions.py)
- call (internal_sessions.py)

They all expected a Coroutine to return, but these are not awaited. Making a test to check them seems to be more tricky than expected, so this will consume more time than expected.

**Comment by oroulet** [comment]
Din noe Try to do everything at once. Choose some simple ones. Also we have tests for xml import. Hope can it be not async?

**Comment by swamper123** [comment]
In server.py is written:
https://github.com/FreeOpcUa/opcua-asyncio/blob/5132c4edee2ae8348e5d960a2f890341b899d916/asyncua/server/server.py#L526

If you follow the path to `xmlimporter.import_xml`, you'll see it is a Coroutine. So the server Method shall await this Coroutine and has to be a Coroutine on his own, shall it?

**Comment by cbergmiller** [comment]
As long as `Server.import_xml` itself is awaited, it will work (because `Server.import_xml` does return a coroutine from `XmlImporter.import_xml`). But for readability it should probably be a async function.

**Comment by swamper123** [comment]
I haven't known this behaviour of coroutines that Coro->Func->Coro is even possible, but well something new learned today. But I would recommened it anyway to change it into a Coro, not just for readability, in case the function may be touched in future, so this would work correctly. But the case `xml_importer` should be in another issue I may do later.
