### ISSUE TITLE
Accidental empty merge commit  aa8105b

### ISSUE THREAD

**Issue by cbergmiller** [FreeOpcUa/opcua-asyncio#19]
@oroulet Sorry for the empty merge commit aa8105b297044d124e37913a9baf5e091bed0c6f
I pulled the master and accidentally pushed it again.
As far as can see no files have been changed by this - should i try to remove the commit?

**Comment by oroulet** [comment]
Yes just remove it before anyone pulls

-------- Original Message --------
On Feb 25, 2019, 11:53, cbergmiller wrote:

-------- Original Message --------

**Comment by cbergmiller** [comment]
Commit was removed.
