### ISSUE TITLE
Client in streaming 

### ISSUE THREAD

**Issue by FIAV1** [FreeOpcUa/opcua-asyncio#190]
Hi, is there a way to setup client in a permanent connection to the server so that it doesn't close after receiving the first message or after some time (like using sleep(n))?

**Comment by oroulet** [comment]
`while True:
    await asyncio.sleep(1)
`
this is the correct and simple way to do it. Although in a real program you will probably want to do many things instead of just sleeping (makes tasks, survey connection etc...)

**Comment by FIAV1** [comment]
Ok thanks!
