### ISSUE TITLE
missing tests from python-opcua

### ISSUE THREAD

**Issue by oroulet** [FreeOpcUa/opcua-asyncio#20]
@cbergmiller do you have any overview of what tests are missing in asyncua compared to python-opcua? Now that I have sync wrapper that seem to completely working, it should in theary be possible to just copy the missing files to this repository, although it would be better to port them to pytest too

**Comment by cbergmiller** [comment]
Sorry for the late answer. I can't remember at waht point i stopped when i was porting the tests to pytest. I may have time over the weekend to look into that.

**Comment by oroulet** [comment]
@cbergmiller I tried haivng a look but could not find any not portes tests (apart from tools, but these tests are bad, I want to refactor them

**Comment by swamper123** [comment]
Are there still some tests missing @cbergmiller @oroulet (it is a longer while ago)?
Otherwise I would add this issue to the ToDo List or close it.

**Comment by oroulet** [comment]
I think we close that one
