### ISSUE TITLE
BadTimeout Error connecting to Frako PQM-1588 OPC-UA DA Server

### ISSUE THREAD

**Issue by elka0711** [FreeOpcUa/opcua-asyncio#22]
`opcua.ua.uaerrors._auto.BadTimeout: The operation timed out.(BadTimeout)`
For a better understandig, with the asyncronious client I get that timeout error. See attachment of the output.dump file
[output.zip](https://github.com/FreeOpcUa/opcua-asyncio/files/2905280/output.zip)

The client IP is 10.2.202.253, the Server IP is 10.2.202.200.
Authentification method is anonymous, no  encryption, no username&password

Exception:
`File "/python-opcua/asyncua/common/node.py", line 149, in get_node_class
result = await self.get_attribute(ua.AttributeIds.NodeClass)`
`File "/coroutines.py", line 109, in __next__`
`File "/python-opcua/asyncua/common/node.py", line 286, in get_attribute
result = await self.server.read(params)`
`File "/coroutines.py", line 109, in __next__`
`File "/python-opcua/asyncua/client/ua_client.py", line 320, in read
data = await self.protocol.send_request(request)`
`File "/coroutines.py", line 109, in __next__`
`File "/python-opcua/asyncua/client/ua_client.py", line 122, in send_request
await asyncio.wait_for(future, timeout if timeout else None)`
`File "/tasks.py", line 362, in wait_for
concurrent.futures._base.TimeoutError`

If testing a connection with the software UaExpert V1.4.4 to the same OPC-UA Server everything is good
![pqm-1588](https://user-images.githubusercontent.com/34133697/53404243-8c774000-39b5-11e9-8fe3-ac85e2945f03.JPG)
[output.zip](https://github.com/FreeOpcUa/opcua-asyncio/files/2905279/output.zip)

**Comment by oroulet** [comment]
you will need to record a session with wireshark both a working one (with uaexpert) and a not working one from python and compare them to try to catch any difference...

**Comment by elka0711** [comment]
Ok, I will try it with wireshark, but it is not so easy, because it's a customer system and I have not full admin rights on their system.
 That output.dump file I generate with tcpdump from our gateway at the customer side.
I'll keep you posted. 
Another  try with your client_minimal.py example file was successfull. Not every time, but sometimes. So I think, may be, it is also a problem with the OPC-UA Server implementation on the PQM device.

**Comment by oroulet** [comment]
I thing tcpdump can dump in a Wireshark friendly format. But you need a session from uaexpert to compare

**Comment by elka0711** [comment]
I know, but I need the admin rights on their system to install and use wireshark for capture the UaExpert.

In my output.dump file I found out that everything runs good as far as time 0.833268 and the timeout comes 10 seconds later at time 10.35665. 
The reason seems to be a UA Secure Converastion problem.
![wireshark_pqm-1588](https://user-images.githubusercontent.com/34133697/53470934-732ccd00-3a63-11e9-8140-8228e80712e9.JPG)

**Comment by oroulet** [comment]
OK. I did not see you attached the tcpdump already. That stuff looks strange. It is a simple read request and the server does not answer.... Can it be some network issue?
I think if it was a session timeout we would get an error messgae from server. Here it just stops sending things. looks like a network or server issue.... it looks like you will need to contact the supplier

**Comment by oroulet** [comment]
you can still record an uaexpert session and try to stop a difference if uaexpert works

**Comment by elka0711** [comment]
I will contact the supplier, because we can exclude a network issue.  
Also interesting is that UaExpert just the same have problem's every minute.
![uaexpert_pqm-1588](https://user-images.githubusercontent.com/34133697/53472708-b6d60580-3a68-11e9-99e5-69380be742b8.JPG)

**Comment by elka0711** [comment]
That's the Trace-Log from UaExpert
[UaExpertTrace.log](https://github.com/FreeOpcUa/opcua-asyncio/files/2909012/UaExpertTrace.log)

**Comment by cbergmiller** [comment]
@elka0711 Any Progress on this issue? Did you hear back from the vendor/maker?

**Comment by cbergmiller** [comment]
I am assuming this problem was resolved or is caused by the server you were using. Feel free to open a new issue otherwise.
