### ISSUE TITLE
0.8.3 -> 0.8.4 changes?

### ISSUE THREAD

**Issue by AndreasHeine** [FreeOpcUa/opcua-asyncio#246]
0.8.4:
![0 8 4](https://user-images.githubusercontent.com/56362817/88091132-ee2de080-cb8e-11ea-8dfc-0d3f33e88afa.PNG)
0.8.3
![0 8 3](https://user-images.githubusercontent.com/56362817/88091124-ea9a5980-cb8e-11ea-8683-ce64de2c9afb.PNG)

!?

**Comment by oroulet** [comment]
Must be something in xml... Needs debugging ;-)

**Comment by AndreasHeine** [comment]
those changes.... -_-°

**Comment by oroulet** [comment]
prosys browser cannot browse DataTypes on opcua-asyncio... might be the same issue...

**Comment by oroulet** [comment]
The bad commit is https://github.com/FreeOpcUa/opcua-asyncio/commit/b0b54cb954c7bd037ff43e1e5236e87a256e8db4  @swamper123 @AndreasHeine

**Comment by oroulet** [comment]
arg wrong. I cheked manually all commits and it seems that first break is the next commit https://github.com/FreeOpcUa/opcua-asyncio/commit/47920a7fe022a8682c833ff99124273943bf3982

**Comment by oroulet** [comment]
bug here: https://github.com/FreeOpcUa/opcua-asyncio/commit/47920a7fe022a8682c833ff99124273943bf3982#diff-373971016c019c1ed89fd42c9829acb8R394

**Comment by AndreasHeine** [comment]
> bug here: 47920a7#diff-373971016c019c1ed89fd42c9829acb8R394

 might explain -> #247

**Comment by AndreasHeine** [comment]
@oroulet looks like the error is back!?
