### ISSUE TITLE
Travis not running in PR

### ISSUE THREAD

**Issue by swamper123** [FreeOpcUa/opcua-asyncio#266]
I just recognised that Travis is not running anymore in our PRs.
Does anyone know why?
Edit: It seems to be an issue since more than 2 days, since @AndreasHeine latest PR wasn't checked either

**Comment by AndreasHeine** [comment]
sounds like we didn't pay the bills ;)

**Comment by swamper123** [comment]
Perhaps we need to add a Bitcoinminer in our repo than as well. :^)
Since the travis file wasn't touched, are we missing any Github-app stuff (or sth. like that)?  @oroulet

**Comment by oroulet** [comment]
I tried to check yesterday but everything looked fine. Must have a look again..

**Comment by swamper123** [comment]
Travis is alive again! Cheers! :)
