### ISSUE TITLE
About server method "register_to_discovery"

### ISSUE THREAD

**Issue by myahuang** [FreeOpcUa/opcua-asyncio#270]
I have find a issue No #733,@brubbel suggested Discovery clients should be outside of server.py code, and I find the method   "register_to_discovery" now is not in the  server class of library "opcua". But in library "asyncua",method   "register_to_discovery" is still in server class. My further question is that how to use this method?Could someone give a example about this method and add it to example folder?
I'm puzzled because even I don't use the method, UaExpert can find the  server, like this:
<img width="384" alt="image" src="https://user-images.githubusercontent.com/57703532/90890226-26be1580-e3ec-11ea-8fbc-deab10eac4d2.png">
but in KepserverEx 6, when I create a new  OPC UA Client chanel, the server can't be discovered,like this;
<img width="284" alt="image" src="https://user-images.githubusercontent.com/57703532/90890609-e612cc00-e3ec-11ea-9f1d-1706a246891c.png">

**Comment by AndreasHeine** [comment]
@myahuang maybe relevant for you https://github.com/FreeOpcUa/opcua-asyncio/pull/1193
