### ISSUE TITLE
Identical browsenames in same Namespace?

### ISSUE THREAD

**Issue by swamper123** [FreeOpcUa/opcua-asyncio#274]
Hey ho together,

I was wondering how a Client gets it's target Node in the end, if it doesn't know it's NodeID.
The only option is via BrowseName (or better: the browsing path). But it is possible to create multiple Nodes with the same Browsename in the same Namespace, which may lead to chaos.

MyObject number one...
![grafik](https://user-images.githubusercontent.com/24408657/91314317-ba119500-e7b6-11ea-9850-09271afaaf71.png)
...and number two.
![grafik](https://user-images.githubusercontent.com/24408657/91314394-cd246500-e7b6-11ea-8e8b-fb785b73ad0a.png)

As I understand the [specs](https://reference.opcfoundation.org/v104/Core/docs/Part3/5.2.4/) here right, it is allowed to create multiple Nodes with the same Browsename, but they can't be in the same Node. 
They can be in the same namespace, but in different paths or they are in different namespaces.

So we may need to add a check before adding the Node to the server, if this Browsename already exists, in the Node where it should be added ( I hope this is understandable?).

Am I missinterpreting the specs?

**Comment by oroulet** [comment]
yes it looks like we should accept several time the same bname as child of a ndoe

**Comment by swamper123** [comment]
Solution provided in #306

**Comment by swamper123** [comment]
Case solved and closed 🕵️
