### ISSUE TITLE
security vulnerability: pickle module

### ISSUE THREAD

**Issue by swamper123** [FreeOpcUa/opcua-asyncio#277]
The pickle module in Python is a hot iron. It is a good serialiser, but the danger to execute unwanted code exists.

Pickle is used here:

https://github.com/FreeOpcUa/opcua-asyncio/blob/3636b610ae17a4c318730399150431afb8a81d5e/asyncua/server/address_space.py#L590

There are multiple options:
- leave as is
- remove them
- add a securitylayer around pickled data and decraypt them while unpickle
- add a logger warning & comments to be carful with that

What do you think about that?

(And would it be a good idea to add an extra Label for security vulnerabilities?)
EDIT: This was found via [bandit](https://github.com/PyCQA/bandit), which also recommends using other xml libraries, but this may be another issue)

**Comment by swamper123** [comment]
*bump* 
No comments on that?

**Comment by AndreasHeine** [comment]
sorry read it but too busy atm 😬 (still want to start with history sql rework)

**Comment by swamper123** [comment]
@AndreasHeine No preassure! There are other contributers here as well with a comment on that topic, I guess/hope?! 😄

**Comment by cbergmiller** [comment]
Are the `load_address_space` and `dump_address_space` used by anyone? Also note that these are blocking methods (will block the event loop). If they are not used i would vote to remove them.
If still needed then `AddressSpace.dump` and `load` could be refactored to serialize the node data as JSON.

**Comment by swamper123** [comment]
I guess this was a "quick&dirty" method to load/dump the whole addressspace for test purposes perhaps? The clean way would be via the xml files.
That these things are blocking is reasonable, because you may pickle an invalid addresspace in the end if it doesn't "freeze" for that time.
A nice JSON dump/load would be nice, indeed.

**Comment by swamper123** [comment]
I just found that `generate_address_space.py` is generating/using a pickle file. We may have to rework that as well then into a JSON alternative.

As well there seems to be an idea that you can load/dump the namespace in a faster way than via xml(? see LazyLoadingDict in address_space), perhaps we could extend that with saved values as well?

**Comment by schroeder-** [comment]
pickel is disabled so closing this
