### ISSUE TITLE
dependency to context manager

### ISSUE THREAD

**Issue by oroulet** [FreeOpcUa/opcua-asyncio#28]
@cbergmiller Why do we have dependency to https://pypi.org/project/asyncio-contextmanager/ ?
It seems to be used at one place in https://github.com/FreeOpcUa/opcua-asyncio/blob/master/asyncua/server/history_sql.py
What was the issue that made it needed?

**Comment by cbergmiller** [comment]
I used it to provide a context handler for opening/closing the DB connection. This could be refactored if you want to remove the dependency.

**Comment by oroulet** [comment]
I do not really like to have a dependency for something which is more like sample code ;-)
and why do we need the context handler? there is only one thread and one task so we can just share one global connection, can't we?

**Comment by cbergmiller** [comment]
I don't have much experience with low level DB access. The cursor could be opened on `init` and closed on `stop`.
