### ISSUE TITLE
git fetch fails because of branch name

### ISSUE THREAD

**Issue by cbergmiller** [FreeOpcUa/opcua-asyncio#286]
I can't fetch this repository any more and i think it is due to the use of the `>` character in a recently introduced branch.
Anyone else having similar trouble?

```
git fetch
error: cannot lock ref 'refs/remotes/origin/Fix-history_sql.py-emitting-node-is-not-the-source-->-sql-error': Unable to create 'PycharmProjects/opcua-asyncio/.git/refs/remotes/origin/Fix-history_sql.py-emitting-node-is-not-the-source-->-sql-error.lock': Invalid argument
From https://github.com/FreeOpcUa/opcua-asyncio
 ! [new branch]      Fix-history_sql.py-emitting-node-is-not-the-source-->-sql-error -> origin/Fix-history_sql.py-emitting-node-is-not-the-source-->-sql-error  (unable to update local ref)
```

**Comment by swamper123** [comment]
![grafik](https://user-images.githubusercontent.com/24408657/93185683-04df5680-f73e-11ea-8514-2c844bc988ca.png)
This realy seems to be an error if you are using console commands (tested on Windows and Linux, same result via cmd). Perhaps UI stuff may handle it in another way.

**Comment by AndreasHeine** [comment]
@swamper123 done!

**Comment by swamper123** [comment]
@AndreasHeine I think it is still there. Have you pushed it?
![grafik](https://user-images.githubusercontent.com/24408657/93299615-9eb60a80-f7f5-11ea-916a-a35ab1bb188f.png)

**Comment by AndreasHeine** [comment]
... some strange things happend must delete the branch!

**Comment by cbergmiller** [comment]
Works again for me, thanks!

**Comment by AndreasHeine** [comment]
sorry about that!

**Comment by swamper123** [comment]
No worries, can happen. :)
