### ISSUE TITLE
Kepware tag browsing issue

### ISSUE THREAD

**Issue by kbotha** [FreeOpcUa/opcua-asyncio#29]
Hi

I'm running an OPC Server in python (server-example.py) and trying to connect to it using an OPC UA Client in Kepware (KEPServerEX6). The connection works but I get an error message when I browse for tags and try to add them. If I manually try to add them using their address (eg. ns=2;i=13) then it works fine.

Browsing for Python OPC Server works:
![image](https://user-images.githubusercontent.com/5255272/56115899-cf40a780-5f64-11e9-8532-2dce1fcdd6e5.png)

Connection settings (password is blank):
![image](https://user-images.githubusercontent.com/5255272/56116001-044cfa00-5f65-11e9-8a2c-59f44de03a65.png)

I can then browse for tags and it shows all of the tags that should be there:
![image](https://user-images.githubusercontent.com/5255272/56116164-7291bc80-5f65-11e9-8084-699087992a02.png)

If I then select one/many of the tags I get the following error message:
![image](https://user-images.githubusercontent.com/5255272/56116334-d9af7100-5f65-11e9-8c4d-4626a7d850c3.png)

Afterwards I can manually go and and tags which works fine.

Am I missing something on the python side? Or is it maybe some Kepware related issue?

Some log from pycharm:
INFO:asyncua.server.internal_server:Created internal session ('127.0.0.1', 65001)
INFO:asyncua.server.internal_server:Create session request
INFO:asyncua.server.internal_server:get endpoint
INFO:asyncua.server.uaprocessor:sending create session response
INFO:asyncua.server.uaprocessor:Activate session request
INFO:asyncua.server.internal_server:activate session
INFO:asyncua.server.internal_server:Activated internal session ('127.0.0.1', 65001) for user User.Anonymous
INFO:asyncua.server.uaprocessor:sending read response
INFO:asyncua.server.uaprocessor:Read request
INFO:asyncua.server.uaprocessor:sending read response
INFO:asyncua.server.uaprocessor:Browse request
INFO:asyncua.server.uaprocessor:sending browse response
INFO:asyncua.server.uaprocessor:Browse request
INFO:asyncua.server.uaprocessor:sending browse response
INFO:asyncua.server.uaprocessor:Read request
INFO:asyncua.server.uaprocessor:sending read response
INFO:asyncua.server.uaprocessor:Read request
INFO:asyncua.server.uaprocessor:sending read response
INFO:asyncua.server.uaprocessor:Read request
INFO:asyncua.server.uaprocessor:sending read response
INFO:asyncua.server.uaprocessor:Read request
INFO:asyncua.server.uaprocessor:sending read response
INFO:asyncua.server.uaprocessor:Browse request
INFO:asyncua.server.uaprocessor:sending browse response
INFO:asyncua.server.uaprocessor:Read request
INFO:asyncua.server.uaprocessor:sending read response
INFO:asyncua.server.uaprocessor:Close session request
!! This comes after I try to add the tags from the browse menu
INFO:asyncua.server.internal_server:close session %s
INFO:asyncua.server.subscription_service:delete subscriptions: []
INFO:asyncua.server.uaprocessor:sending close session response
INFO:asyncua.server.binary_server_asyncio:processor returned False, we close connection from ('127.0.0.1', 65001)
INFO:asyncua.server.binary_server_asyncio:Lost connection from ('127.0.0.1', 65001), None
INFO:asyncua.server.uaprocessor:Cleanup client connection: ('127.0.0.1', 65001)
INFO:asyncua.server.internal_server:close session %s
INFO:asyncua.server.subscription_service:delete subscriptions: []

**Comment by kbotha** [comment]
Kepware actually can't read and of the tags from the Python OPC Server

**Comment by oroulet** [comment]
If it does not work then we should have an open bug report

**Comment by kbotha** [comment]
Ok, I'll make one
