### ISSUE TITLE
GUID with single zero byte misidentified as null identifier

### ISSUE THREAD

**Issue by Randelung** [FreeOpcUa/opcua-asyncio#290]
https://github.com/FreeOpcUa/opcua-asyncio/blob/75adf4f885a71ef3b8b49711dc12a6ed8dab87d8/asyncua/ua/uatypes.py#L332

It matches a single byte instead of all of them being zero, e. g. `0032b2d5-c219-4524-8df5-5490a2109e9b`.
The consequence is that instead of the supplied GUID a new integer identifier is generated.

I can't say for sure that this is not an illegal node identifier, but

> Each value is formatted as a hexadecimal number with padded zeros.
(https://reference.opcfoundation.org/v104/Core/docs/Part6/5.1.3/)

seems to suggest multiple (especially leading) zeros can exist in a GUID.

I also found this:

> A Node in the AddressSpace shall not have a null as its NodeId.
(https://reference.opcfoundation.org/v104/Core/docs/Part3/8.2.4/)

but I think this references an all-zeros identifier, not containing a single zero byte.
Other than that there seems to be no restrictions.

My suggestion (which I'll gladly submit if you agree) is to replace the regex check with a check for an all zero bytes array.

```python
if self.NodeIdType == NodeIdType.Guid and self.Identifier.bytes == b'\00'*16:
```

**Comment by cbergmiller** [comment]
I think you are right this looks like a bug.
Can you create a pull request?
I would also suggest adding a test to `tests/test_unit.py` (see `test_null_guid`) to prevent regression.
