### ISSUE TITLE
[Bug Report] Kepware (and OPC Expert) can't read tags from Python OPC Server

### ISSUE THREAD

**Issue by kgithubaccount** [FreeOpcUa/opcua-asyncio#31]
Hi

I have a UA OPC Server running in python (using the server-example.py) python script.

I am able to read tags from the server using one of the example client scripts.

In Kepware I get an error when I try to add browsed tags and when I try to manually add tags using their address I am also not able to view the tags.

Using OPC Expert I get another error (not sure how related they are, error messages seem different)

**Python**
I am running server-example.py

**Kepware:**
I add a UA Client channel with the following settings:
![image](https://user-images.githubusercontent.com/5255272/56192374-7a696380-602e-11e9-8454-e34b83d39255.png)
![image](https://user-images.githubusercontent.com/5255272/56192403-8a814300-602e-11e9-9564-b1db66707faa.png)
I can browse tags and all looks good
![image](https://user-images.githubusercontent.com/5255272/56192434-a258c700-602e-11e9-9b6b-a632ab34cb16.png)
But when I click OK, Kepware GUI either crashes without an error message, or I get the following message "Failed to browse tags"

I then don't try to add any tags, and use the default device settings:
![image](https://user-images.githubusercontent.com/5255272/56192630-1f843c00-602f-11e9-909b-630320083d02.png)
Then manually add a tag using its address:
![image](https://user-images.githubusercontent.com/5255272/56192719-4c385380-602f-11e9-865a-9f752e1a8276.png)
But the tag doesn't work:
![image](https://user-images.githubusercontent.com/5255272/56192792-75f17a80-602f-11e9-9052-4965783fd981.png)
(OPC Expert shows that there is an error "Not Connected 8")

**OPC Expert**
By default the python OPC Server doesn't show up
![image](https://user-images.githubusercontent.com/5255272/56192959-d8e31180-602f-11e9-81f8-ffa68b3547f6.png)
I manually add it using:
![image](https://user-images.githubusercontent.com/5255272/56193004-f6b07680-602f-11e9-9152-cc83230b53fa.png)
It adds the server and it looks good:
![image](https://user-images.githubusercontent.com/5255272/56193162-4727d400-6030-11e9-941a-ec050143e0f7.png)

It doesn't connect, the logs show:
![image](https://user-images.githubusercontent.com/5255272/56193050-134cae80-6030-11e9-9c0a-a68b4010f5d4.png)

**Comment by mehow2** [comment]
Hi, do you have any workaround for this issue?
