### ISSUE TITLE
UA Client needlessly warns about the KeepAlive Message ("NotificationMessage is None.")

### ISSUE THREAD

**Issue by ryancu7** [FreeOpcUa/opcua-asyncio#345]
My open62541 server sends a keep-alive message every 10 seconds when the Python client has a subscription. This is expected according to the OPC UA spec (see also #263). However, the Python client logs a warning every time one of these messages are received.

> NotificationMessage is None.

This comes from https://github.com/FreeOpcUa/opcua-asyncio/blob/6c504f24387b7fca2fae58546717d8200465ef16/asyncua/common/subscription.py#L107

This should be removed.

Also reported here: https://github.com/FreeOpcUa/python-opcua/issues/1137

**Comment by oroulet** [comment]
done and released
