### ISSUE TITLE
Travis python 3.9 pip pytest --upgrade installs all versions of pytest.

### ISSUE THREAD

**Issue by swamper123** [FreeOpcUa/opcua-asyncio#364]
Something went wrong here.

![grafik](https://user-images.githubusercontent.com/24408657/102491262-384cbc80-4070-11eb-9f90-6bf096d0e1b1.png)

This causes 3.9 to run longer than the other versions, where it doesn't happen.

[
Happened in that PR](https://travis-ci.org/github/FreeOpcUa/opcua-asyncio/jobs/750209966)

**Comment by oroulet** [comment]
moved from travis to github actions and actions pass with 3.9
