### ISSUE TITLE
Exporting type-stubs for supporting pyright

### ISSUE THREAD

**Issue by maneetgoyal** [FreeOpcUa/opcua-asyncio#383]
Can [type-stubs](https://github.com/microsoft/pyright/blob/master/docs/type-stubs.md) be shipped with this library for supporting type checking with pyright?

**Comment by AndreasHeine** [comment]
thats actually not an opcua related issue! 
could you please use:
https://github.com/FreeOpcUa/opcua-asyncio/discussions
or
https://gitter.im/FreeOpcUa/opcua-asyncio
to ask Questions.

**Comment by maneetgoyal** [comment]
@AndreasHeine Sorry about that. Closing it and creating a new discussion.

**Comment by maneetgoyal** [comment]
Created https://github.com/FreeOpcUa/opcua-asyncio/discussions/384
