### ISSUE TITLE
Test `test_xml_method` is failing.

### ISSUE THREAD

**Issue by cbergmiller** [FreeOpcUa/opcua-asyncio#4]
When trying to re-import the nodes from the created XML file, the tests fails with the error `BadParentNodeIdInvalid: The parent node id does not to refer to a valid node.(BadParentNodeIdInvalid)`.

**Comment by oroulet** [comment]
with main branch I am also getting some strange things when importating some xml files. there is something wrong somewhere. I suppose this is link to this https://github.com/FreeOpcUa/python-opcua/commit/48c2d4c4d1c748ebb761f07120dfe6c332987ab2
