### ISSUE TITLE
Unable to read all Child nodes and Sub-Child nodes variable data at one shot.

### ISSUE THREAD

**Issue by arunkrh123** [FreeOpcUa/opcua-asyncio#463]
### **I am able to read the Node and immediate variable data values using the below code.**

async def readValueDirect(NodeName, VarName, SecurityMode='None', UserIdentityTokenType='Anonymous', 
     serverCreds=None, authCredentials=None):
 
    DISCOVERY_SERVER_ENDPOINT = 'opc.tcp://{}:{}'.format(str(IP), str(PORT))
    client = Client(DISCOVERY_SERVER_ENDPOINT)
    print("Getclient:", await get_client(client, SecurityMode, UserIdentityTokenType, authCredentials, serverCreds))
    try:
        async with client:
          uri = 'http://opcfoundation.org/UA/'
          try:
              idx = await client.get_namespace_index(uri)
          except ua.UaError as exec:
              print(str(exec))
          # Now getting a variable node using its browse path
          CHILDRENS = await client.nodes.objects.get_children()
          
          for N in CHILDRENS:
              GetN = client.get_node(N)
              node_variables = await GetN.get_variables()
              for V in node_variables:
                  V1 = await GetN.read_browse_name()
                  V2 = await V.read_browse_name()
                  V1 = str(V1)
                  V2 = str(V2)
                  V1 = V1[16:-1]
                  V2 = V2[16:-1]
                  V3 = str(V1) + "-" + str(V2)
                  NODE = V
                  NODE = str(NODE)
                  NODE = NODE[26:-2]
                  NS = V
                  NS = str(NS)
                  NS = NS[22:-7]
                  PN = await V.get_parent()
                  PN = str(PN)
                  PN = PN[26:-2]
                  Dtype = str(await V.read_data_value())
                  Dtype = re.search('(?<=VariantType.)\w+', Dtype)
                  Dtype = str(Dtype[0])
                  VarValue = await  V.read_value()
                  ObjectDict[V3] = {"GetNName": await GetN.read_browse_name(), "DataType": Dtype,"NodeBrowseName": await V.read_browse_name(), "Nodes": V,
                                        "PARENTNODE": await V.get_parent(), "DisplayName": await V.read_display_name(), "NodeID": V.nodeid, "BrowseName": await V.read_browse_name(),
                                        "DataValue": await  V.read_data_value(), "Value": VarValue, "VName": V, "Namespace": NS, "Index": NODE, "ParentIndex": PN}
          pprint.pprint(ObjectDict)

    except TimeoutError as exec:
        print(exec)
        traceback.print_exc()
        return 0
def ReadNodeValue(NodeName, VarName, SecurityMode='None', UserIdentityTokenType='Anonymous', 
      serverCreds=None, authCredentials=None):
      p = asyncio.run(readValueDirect(NodeName, VarName, SecurityMode=SecurityMode, 
             UserIdentityTokenType=UserIdentityTokenType, serverCreds=serverCreds,authCredentials=authCredentials))
      return p

SetClient('192.168.204.7','4840') # Succesfully establishing the communication
x= ReadNodeValue("Server", "ServerStatus") 

When i use **'CHILDRENS = await client.nodes.objects.get_children()'** in the code I am not getting all Sub-Child Node-ID.

Is there any way I can get all the **CHILD and SUB-CHILD** node variable values into a dictionary?

Please refer the below image for understanding the Node hierarchy.

![image](https://user-images.githubusercontent.com/79836676/109480201-41f79500-7aa1-11eb-9b7c-ee00145f010a.png)

Thanks in advance.

Regards,
Arunkumar H

**Comment by AndreasHeine** [comment]
https://github.com/FreeOpcUa/opcua-asyncio/blob/12c0e7a05d756219ac56448edf7f78a030a3d049/asyncua/common/node.py#L323

get_children() returns a list of nodes (Node-Class-Instances) like in the docstring:

> Get all children of a node. By default hierarchical references and all node classes are returned.

what childs do you miss? example?
what do you mean with `I am not getting all Sub-Child Node-ID` ???

**Comment by Koseng** [comment]
Hi,
get_children() just gives you the next layer. In ua_utils.py there are helper methods to collect all children recursively.

**Example to collect all variables:**
```
from asyncua.common import ua_utils
   
nodeList = await ua_utils.get_node_children(myStartNode)
for n in nodeList:
     nodeClass = await n.read_node_class()
     if nodeClass == ua.NodeClass.Variable:
             # do something
```

**Comment by arunkrh123** [comment]
Hi Koseng and AndreasHeine,

Thanks for your response.

I have tried the code which @Koseng shared in the comment section, I am able to read all the child and sub-child nodes. But I am getting error  when I try to read the value using this NodeIDs.

Note: All attributes are not supported by few node variables. Is there any way to identify what attributes are supported by the node variable?

Code:
CHILDRENS = await client.nodes.objects.get_children()
          allVariables = []
          for N in CHILDRENS:
              ######################
              from asyncua.common import ua_utils

              allVariables = []

              nodeList = await ua_utils.get_node_children(N)

              print("test node list: ",nodeList)

              for n in nodeList:
                  nodeClass = await n.read_node_class()
                  if nodeClass == ua.NodeClass.Variable:
                      if nodeClass not in allVariables:
                         allVariables.append(n)
                      #val= await  ua.NodeClass.value

              for nodeID in allVariables:
                  GetNtest = client.get_node(nodeID)
                  Value = await GetNtest.read_value()
                  BrowseName = await GetNtest.read_browse_name()

                  print("Name",BrowseName," Value:",Value)


![image](https://user-images.githubusercontent.com/79836676/109690327-3e9d0000-7bac-11eb-9e81-3f5196b9083e.png)

Kindly please help me to resolve this issue. My objective is to read all NodeIDs and their corresponding node value to a dictionary as Key value pair.

Kindly please help to resolve this issue.

Thanks and Regards,
Arunkumar H

**Comment by arunkrh123** [comment]
Hi @Koseng,

Thanks for your quick response.

I am getting following error when I run the above code. 

![image](https://user-images.githubusercontent.com/79836676/109702374-292ed280-7bba-11eb-9f8b-5df148c2185d.png)


INFO:asyncua.client.ua_client.UaClient:browse
INFO:asyncua.client.ua_client.UaClient:browse
INFO:asyncua.client.ua_client.UaClient:browse
[Node(ns=4;s=|vprop|PM5630-2ETH_OPC UA.Application.SerialNumber), Node(ns=4;s=|vprop|PM5630-2ETH_OPC UA.Application.RevisionCounter), Node(ns=4;s=|vprop|PM5630-2ETH_OPC UA.Application.Manufacturer), Node(ns=4;s=|vprop|PM5630-2ETH_OPC UA.Application.Model), Node(ns=4;s=|vprop|PM5630-2ETH_OPC UA.Application.DeviceManual), Node(ns=4;s=|vprop|PM5630-2ETH_OPC UA.Application.DeviceRevision), Node(ns=4;s=|vprop|PM5630-2ETH_OPC UA.Application.SoftwareRevision), Node(ns=4;s=|vprop|PM5630-2ETH_OPC UA.Application.HardwareRevision), Node(ns=4;s=|var|PM5630-2ETH_OPC UA.Application.POU_1.a1), Node(ns=4;s=|var|PM5630-2ETH_OPC UA.Application.POU_1.ai1), Node(ns=4;s=|var|PM5630-2ETH_OPC UA.Application.Constants.CompilerVersion), Node(ns=4;s=|var|PM5630-2ETH_OPC UA.Application.Constants.CompilerVersion.uiMajor), Node(ns=4;s=|var|PM5630-2ETH_OPC UA.Application.Constants.CompilerVersion.uiMinor), Node(ns=4;s=|var|PM5630-2ETH_OPC UA.Application.Constants.CompilerVersion.uiServicePack), Node(ns=4;s=|var|PM5630-2ETH_OPC UA.Application.Constants.CompilerVersion.uiPatch), Node(ns=4;s=|var|PM5630-2ETH_OPC UA.Application.Constants.RuntimeVersion), Node(ns=4;s=|var|PM5630-2ETH_OPC UA.Application.Constants.RuntimeVersion.uiMajor), Node(ns=4;s=|var|PM5630-2ETH_OPC UA.Application.Constants.RuntimeVersion.uiMinor), Node(ns=4;s=|var|PM5630-2ETH_OPC UA.Application.Constants.RuntimeVersion.uiServicePack), Node(ns=4;s=|var|PM5630-2ETH_OPC UA.Application.Constants.RuntimeVersion.uiPatch), Node(ns=4;s=|var|PM5630-2ETH_OPC UA.Application.IoConfig_Globals_Mapping.ai1), Node(ns=4;s=|var|PM5630-2ETH_OPC UA.Application.IoConfig_Globals_Mapping.ai2), Node(ns=4;s=|var|PM5630-2ETH_OPC UA.Application.IoConfig_Globals_Mapping.ai3_1), Node(ns=4;s=|var|PM5630-2ETH_OPC UA.Application.IoConfig_Globals_Mapping.ai4), Node(ns=4;s=|var|PM5630-2ETH_OPC UA.Application.IoConfig_Globals_Mapping.ao1), Node(ns=4;s=|var|PM5630-2ETH_OPC UA.Application.IoConfig_Globals_Mapping.ao2), Node(ns=4;s=|var|PM5630-2ETH_OPC UA.Application.IoConfig_Globals_Mapping.ao3), Node(ns=4;s=|var|PM5630-2ETH_OPC UA.Application.IoConfig_Globals_Mapping.ao4), Node(ns=4;s=|var|PM5630-2ETH_OPC UA.Application.IoConfig_Globals_Mapping.DI1), Node(ns=4;s=|var|PM5630-2ETH_OPC UA.Application.IoConfig_Globals_Mapping.DI10), Node(ns=4;s=|var|PM5630-2ETH_OPC UA.Application.IoConfig_Globals_Mapping.DI11), Node(ns=4;s=|var|PM5630-2ETH_OPC UA.Application.IoConfig_Globals_Mapping.DI12), Node(ns=4;s=|var|PM5630-2ETH_OPC UA.Application.IoConfig_Globals_Mapping.DI13), Node(ns=4;s=|var|PM5630-2ETH_OPC UA.Application.IoConfig_Globals_Mapping.DI14), Node(ns=4;s=|var|PM5630-2ETH_OPC UA.Application.IoConfig_Globals_Mapping.DI15), Node(ns=4;s=|var|PM5630-2ETH_OPC UA.Application.IoConfig_Globals_Mapping.DI16), Node(ns=4;s=|var|PM5630-2ETH_OPC UA.Application.IoConfig_Globals_Mapping.DI17), Node(ns=4;s=|var|PM5630-2ETH_OPC UA.Application.IoConfig_Globals_Mapping.DI18), Node(ns=4;s=|var|PM5630-2ETH_OPC UA.Application.IoConfig_Globals_Mapping.DI19), Node(ns=4;s=|var|PM5630-2ETH_OPC UA.Application.IoConfig_Globals_Mapping.DI2), Node(ns=4;s=|var|PM5630-2ETH_OPC UA.Application.IoConfig_Globals_Mapping.DI20), Node(ns=4;s=|var|PM5630-2ETH_OPC UA.Application.IoConfig_Globals_Mapping.DI21), Node(ns=4;s=|var|PM5630-2ETH_OPC UA.Application.IoConfig_Globals_Mapping.DI22), Node(ns=4;s=|var|PM5630-2ETH_OPC UA.Application.IoConfig_Globals_Mapping.DI23), Node(ns=4;s=|var|PM5630-2ETH_OPC UA.Application.IoConfig_Globals_Mapping.DI24), Node(ns=4;s=|var|PM5630-2ETH_OPC UA.Application.IoConfig_Globals_Mapping.DI25), Node(ns=4;s=|var|PM5630-2ETH_OPC UA.Application.IoConfig_Globals_Mapping.DI26), Node(ns=4;s=|var|PM5630-2ETH_OPC UA.Application.IoConfig_Globals_Mapping.DI27), Node(ns=4;s=|var|PM5630-2ETH_OPC UA.Application.IoConfig_Globals_Mapping.DI28), Node(ns=4;s=|var|PM5630-2ETH_OPC UA.Application.IoConfig_Globals_Mapping.DI29), Node(ns=4;s=|var|PM5630-2ETH_OPC UA.Application.IoConfig_Globals_Mapping.DI3), Node(ns=4;s=|var|PM5630-2ETH_OPC UA.Application.IoConfig_Globals_Mapping.DI30), Node(ns=4;s=|var|PM5630-2ETH_OPC UA.Application.IoConfig_Globals_Mapping.DI31), Node(ns=4;s=|var|PM5630-2ETH_OPC UA.Application.IoConfig_Globals_Mapping.DI32), Node(ns=4;s=|var|PM5630-2ETH_OPC UA.Application.IoConfig_Globals_Mapping.DI4), Node(ns=4;s=|var|PM5630-2ETH_OPC UA.Application.IoConfig_Globals_Mapping.DI5), Node(ns=4;s=|var|PM5630-2ETH_OPC UA.Application.IoConfig_Globals_Mapping.DI6), Node(ns=4;s=|var|PM5630-2ETH_OPC UA.Application.IoConfig_Globals_Mapping.DI7), Node(ns=4;s=|var|PM5630-2ETH_OPC UA.Application.IoConfig_Globals_Mapping.DI8), Node(ns=4;s=|var|PM5630-2ETH_OPC UA.Application.IoConfig_Globals_Mapping.DI9), Node(ns=4;s=|var|PM5630-2ETH_OPC UA.Application.IoConfig_Globals_Mapping.do1), Node(ns=4;s=|var|PM5630-2ETH_OPC UA.Application.IoConfig_Globals_Mapping.do10), Node(ns=4;s=|var|PM5630-2ETH_OPC UA.Application.IoConfig_Globals_Mapping.do11), Node(ns=4;s=|var|PM5630-2ETH_OPC UA.Application.IoConfig_Globals_Mapping.do12), Node(ns=4;s=|var|PM5630-2ETH_OPC UA.Application.IoConfig_Globals_Mapping.do13), Node(ns=4;s=|var|PM5630-2ETH_OPC UA.Application.IoConfig_Globals_Mapping.do14), Node(ns=4;s=|var|PM5630-2ETH_OPC UA.Application.IoConfig_Globals_Mapping.do15), Node(ns=4;s=|var|PM5630-2ETH_OPC UA.Application.IoConfig_Globals_Mapping.do16), Node(ns=4;s=|var|PM5630-2ETH_OPC UA.Application.IoConfig_Globals_Mapping.do2), Node(ns=4;s=|var|PM5630-2ETH_OPC UA.Application.IoConfig_Globals_Mapping.do3), Node(ns=4;s=|var|PM5630-2ETH_OPC UA.Application.IoConfig_Globals_Mapping.do4), Node(ns=4;s=|var|PM5630-2ETH_OPC UA.Application.IoConfig_Globals_Mapping.do5), Node(ns=4;s=|var|PM5630-2ETH_OPC UA.Application.IoConfig_Globals_Mapping.do6), Node(ns=4;s=|var|PM5630-2ETH_OPC UA.Application.IoConfig_Globals_Mapping.do7), Node(ns=4;s=|var|PM5630-2ETH_OPC UA.Application.IoConfig_Globals_Mapping.do8), Node(ns=4;s=|var|PM5630-2ETH_OPC UA.Application.IoConfig_Globals_Mapping.do9), Node(i=11314), Node(i=11313), Node(i=11312), Node(i=3709), Node(i=2294), Node(i=2290), Node(i=2275), Node(i=2288), Node(i=2287), Node(i=2286), Node(i=2285), Node(i=2284), Node(i=2282), Node(i=2281), Node(i=3705), Node(i=2279), Node(i=2278), Node(i=2277), Node(i=2276), Node(i=11707), Node(i=11712), Node(i=11711), Node(i=11705), Node(i=11710), Node(i=11714), Node(i=3704), Node(i=2737), Node(i=2736), Node(i=2735), Node(i=2272), Node(i=2271), Node(i=2269), Node(i=2994), Node(i=2267), Node(i=2256), Node(i=2993), Node(i=2992), Node(i=2260), Node(i=2266), Node(i=2265), Node(i=2264), Node(i=2261), Node(i=2263), Node(i=2262), Node(i=2259), Node(i=2258), Node(i=2257), Node(i=2255), Node(i=2254), Node(ns=4;s=|vprop|PM5630-2ETH_OPC UA.Application.SerialNumber), Node(ns=4;s=|vprop|PM5630-2ETH_OPC UA.Application.RevisionCounter), Node(ns=4;s=|vprop|PM5630-2ETH_OPC UA.Application.Manufacturer), Node(ns=4;s=|vprop|PM5630-2ETH_OPC UA.Application.Model), Node(ns=4;s=|vprop|PM5630-2ETH_OPC UA.Application.DeviceManual), Node(ns=4;s=|vprop|PM5630-2ETH_OPC UA.Application.DeviceRevision), Node(ns=4;s=|vprop|PM5630-2ETH_OPC UA.Application.SoftwareRevision), Node(ns=4;s=|vprop|PM5630-2ETH_OPC UA.Application.HardwareRevision), Node(ns=4;s=|var|PM5630-2ETH_OPC UA.Application.POU_1.a1), Node(ns=4;s=|var|PM5630-2ETH_OPC UA.Application.POU_1.ai1), Node(ns=4;s=|var|PM5630-2ETH_OPC UA.Application.Constants.CompilerVersion), Node(ns=4;s=|var|PM5630-2ETH_OPC UA.Application.Constants.CompilerVersion.uiMajor), Node(ns=4;s=|var|PM5630-2ETH_OPC UA.Application.Constants.CompilerVersion.uiMinor), Node(ns=4;s=|var|PM5630-2ETH_OPC UA.Application.Constants.CompilerVersion.uiServicePack), Node(ns=4;s=|var|PM5630-2ETH_OPC UA.Application.Constants.CompilerVersion.uiPatch), Node(ns=4;s=|var|PM5630-2ETH_OPC UA.Application.Constants.RuntimeVersion), Node(ns=4;s=|var|PM5630-2ETH_OPC UA.Application.Constants.RuntimeVersion.uiMajor), Node(ns=4;s=|var|PM5630-2ETH_OPC UA.Application.Constants.RuntimeVersion.uiMinor), Node(ns=4;s=|var|PM5630-2ETH_OPC UA.Application.Constants.RuntimeVersion.uiServicePack), Node(ns=4;s=|var|PM5630-2ETH_OPC UA.Application.Constants.RuntimeVersion.uiPatch), Node(ns=4;s=|var|PM5630-2ETH_OPC UA.Application.IoConfig_Globals_Mapping.ai1), Node(ns=4;s=|var|PM5630-2ETH_OPC UA.Application.IoConfig_Globals_Mapping.ai2), Node(ns=4;s=|var|PM5630-2ETH_OPC UA.Application.IoConfig_Globals_Mapping.ai3_1), Node(ns=4;s=|var|PM5630-2ETH_OPC UA.Application.IoConfig_Globals_Mapping.ai4), Node(ns=4;s=|var|PM5630-2ETH_OPC UA.Application.IoConfig_Globals_Mapping.ao1), Node(ns=4;s=|var|PM5630-2ETH_OPC UA.Application.IoConfig_Globals_Mapping.ao2), Node(ns=4;s=|var|PM5630-2ETH_OPC UA.Application.IoConfig_Globals_Mapping.ao3), Node(ns=4;s=|var|PM5630-2ETH_OPC UA.Application.IoConfig_Globals_Mapping.ao4), Node(ns=4;s=|var|PM5630-2ETH_OPC UA.Application.IoConfig_Globals_Mapping.DI1), Node(ns=4;s=|var|PM5630-2ETH_OPC UA.Application.IoConfig_Globals_Mapping.DI10), Node(ns=4;s=|var|PM5630-2ETH_OPC UA.Application.IoConfig_Globals_Mapping.DI11), Node(ns=4;s=|var|PM5630-2ETH_OPC UA.Application.IoConfig_Globals_Mapping.DI12), Node(ns=4;s=|var|PM5630-2ETH_OPC UA.Application.IoConfig_Globals_Mapping.DI13), Node(ns=4;s=|var|PM5630-2ETH_OPC UA.Application.IoConfig_Globals_Mapping.DI14), Node(ns=4;s=|var|PM5630-2ETH_OPC UA.Application.IoConfig_Globals_Mapping.DI15), Node(ns=4;s=|var|PM5630-2ETH_OPC UA.Application.IoConfig_Globals_Mapping.DI16), Node(ns=4;s=|var|PM5630-2ETH_OPC UA.Application.IoConfig_Globals_Mapping.DI17), Node(ns=4;s=|var|PM5630-2ETH_OPC UA.Application.IoConfig_Globals_Mapping.DI18), Node(ns=4;s=|var|PM5630-2ETH_OPC UA.Application.IoConfig_Globals_Mapping.DI19), Node(ns=4;s=|var|PM5630-2ETH_OPC UA.Application.IoConfig_Globals_Mapping.DI2), Node(ns=4;s=|var|PM5630-2ETH_OPC UA.Application.IoConfig_Globals_Mapping.DI20), Node(ns=4;s=|var|PM5630-2ETH_OPC UA.Application.IoConfig_Globals_Mapping.DI21), Node(ns=4;s=|var|PM5630-2ETH_OPC UA.Application.IoConfig_Globals_Mapping.DI22), Node(ns=4;s=|var|PM5630-2ETH_OPC UA.Application.IoConfig_Globals_Mapping.DI23), Node(ns=4;s=|var|PM5630-2ETH_OPC UA.Application.IoConfig_Globals_Mapping.DI24), Node(ns=4;s=|var|PM5630-2ETH_OPC UA.Application.IoConfig_Globals_Mapping.DI25), Node(ns=4;s=|var|PM5630-2ETH_OPC UA.Application.IoConfig_Globals_Mapping.DI26), Node(ns=4;s=|var|PM5630-2ETH_OPC UA.Application.IoConfig_Globals_Mapping.DI27), Node(ns=4;s=|var|PM5630-2ETH_OPC UA.Application.IoConfig_Globals_Mapping.DI28), Node(ns=4;s=|var|PM5630-2ETH_OPC UA.Application.IoConfig_Globals_Mapping.DI29), Node(ns=4;s=|var|PM5630-2ETH_OPC UA.Application.IoConfig_Globals_Mapping.DI3), Node(ns=4;s=|var|PM5630-2ETH_OPC UA.Application.IoConfig_Globals_Mapping.DI30), Node(ns=4;s=|var|PM5630-2ETH_OPC UA.Application.IoConfig_Globals_Mapping.DI31), Node(ns=4;s=|var|PM5630-2ETH_OPC UA.Application.IoConfig_Globals_Mapping.DI32), Node(ns=4;s=|var|PM5630-2ETH_OPC UA.Application.IoConfig_Globals_Mapping.DI4), Node(ns=4;s=|var|PM5630-2ETH_OPC UA.Application.IoConfig_Globals_Mapping.DI5), Node(ns=4;s=|var|PM5630-2ETH_OPC UA.Application.IoConfig_Globals_Mapping.DI6), Node(ns=4;s=|var|PM5630-2ETH_OPC UA.Application.IoConfig_Globals_Mapping.DI7), Node(ns=4;s=|var|PM5630-2ETH_OPC UA.Application.IoConfig_Globals_Mapping.DI8), Node(ns=4;s=|var|PM5630-2ETH_OPC UA.Application.IoConfig_Globals_Mapping.DI9), Node(ns=4;s=|var|PM5630-2ETH_OPC UA.Application.IoConfig_Globals_Mapping.do1), Node(ns=4;s=|var|PM5630-2ETH_OPC UA.Application.IoConfig_Globals_Mapping.do10), Node(ns=4;s=|var|PM5630-2ETH_OPC UA.Application.IoConfig_Globals_Mapping.do11), Node(ns=4;s=|var|PM5630-2ETH_OPC UA.Application.IoConfig_Globals_Mapping.do12), Node(ns=4;s=|var|PM5630-2ETH_OPC UA.Application.IoConfig_Globals_Mapping.do13), Node(ns=4;s=|var|PM5630-2ETH_OPC UA.Application.IoConfig_Globals_Mapping.do14), Node(ns=4;s=|var|PM5630-2ETH_OPC UA.Application.IoConfig_Globals_Mapping.do15), Node(ns=4;s=|var|PM5630-2ETH_OPC UA.Application.IoConfig_Globals_Mapping.do16), Node(ns=4;s=|var|PM5630-2ETH_OPC UA.Application.IoConfig_Globals_Mapping.do2), Node(ns=4;s=|var|PM5630-2ETH_OPC UA.Application.IoConfig_Globals_Mapping.do3), Node(ns=4;s=|var|PM5630-2ETH_OPC UA.Application.IoConfig_Globals_Mapping.do4), Node(ns=4;s=|var|PM5630-2ETH_OPC UA.Application.IoConfig_Globals_Mapping.do5), Node(ns=4;s=|var|PM5630-2ETH_OPC UA.Application.IoConfig_Globals_Mapping.do6), Node(ns=4;s=|var|PM5630-2ETH_OPC UA.Application.IoConfig_Globals_Mapping.do7), Node(ns=4;s=|var|PM5630-2ETH_OPC UA.Application.IoConfig_Globals_Mapping.do8), Node(ns=4;s=|var|PM5630-2ETH_OPC UA.Application.IoConfig_Globals_Mapping.do9)]
ns=4;s=|vprop|PM5630-2ETH_OPC UA.Application.SerialNumber None
ns=4;s=|vprop|PM5630-2ETH_OPC UA.Application.RevisionCounter 0
ns=4;s=|vprop|PM5630-2ETH_OPC UA.Application.Manufacturer LocalizedText(Encoding:3, Locale:en-Us, Text:)
ns=4;s=|vprop|PM5630-2ETH_OPC UA.Application.Model LocalizedText(Encoding:3, Locale:en-Us, Text:Application)
ns=4;s=|vprop|PM5630-2ETH_OPC UA.Application.DeviceManual 
ns=4;s=|vprop|PM5630-2ETH_OPC UA.Application.DeviceRevision None
ns=4;s=|vprop|PM5630-2ETH_OPC UA.Application.SoftwareRevision 
ns=4;s=|vprop|PM5630-2ETH_OPC UA.Application.HardwareRevision None
ns=4;s=|var|PM5630-2ETH_OPC UA.Application.POU_1.a1 511
ns=4;s=|var|PM5630-2ETH_OPC UA.Application.POU_1.ai1 1648
INFO:asyncua.client.client:disconnect
INFO:asyncua.client.ua_client.UaClient:close_session
INFO:asyncua.client.ua_client.UASocketProtocol:close_secure_channel
INFO:asyncua.client.ua_client.UASocketProtocol:Request to close socket received
INFO:asyncua.client.ua_client.UASocketProtocol:Socket has closed connection
Traceback (most recent call last):
  File "C:/Users/arunkumar.h/PycharmProjects/MySampleTestingOPCUA/Read value.py", line 448, in <module>
    x= ReadNodeValue("Server", "ServerStatus")
  File "C:/Users/arunkumar.h/PycharmProjects/MySampleTestingOPCUA/Read value.py", line 349, in ReadNodeValue
    authCredentials=authCredentials))
  File "C:\Users\arunkumar.h\AppData\Local\Programs\Python\Python37\lib\asyncio\runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "C:\Users\arunkumar.h\AppData\Local\Programs\Python\Python37\lib\asyncio\base_events.py", line 587, in run_until_complete
    return future.result()
  File "C:/Users/arunkumar.h/PycharmProjects/MySampleTestingOPCUA/Read value.py", line 164, in readValueDirect
    value = await node.read_value()
  File "C:\Users\arunkumar.h\Desktop\HMProjects\HMAutomation\intsdn01.1\venv\lib\site-packages\asyncua\common\node.py", line 178, in read_value
    result = await self.read_data_value()
  File "C:\Users\arunkumar.h\Desktop\HMProjects\HMAutomation\intsdn01.1\venv\lib\site-packages\asyncua\common\node.py", line 189, in read_data_value
    return await self.read_attribute(ua.AttributeIds.Value)
  File "C:\Users\arunkumar.h\Desktop\HMProjects\HMAutomation\intsdn01.1\venv\lib\site-packages\asyncua\common\node.py", line 301, in read_attribute
    result[0].StatusCode.check()
  File "C:\Users\arunkumar.h\Desktop\HMProjects\HMAutomation\intsdn01.1\venv\lib\site-packages\asyncua\ua\uatypes.py", line 220, in check
    raise UaStatusCodeError(self.value)
asyncua.ua.uaerrors._auto.BadDataUnavailable: "Expected data is unavailable for the requested time range due to an un-mounted volume, an off-line archive or tape, or similar reason for temporary unavailability."(BadDataUnavailable)

Process finished with exit code 1

Appreciate your help.

Thanks,
Arunkumar H

**Comment by omidfathi** [comment]
Hello again

There is a new problem, to collecting the values an error happened "asyncua.common.utils.NotEnoughData"
![Screenshot from 2022-06-29 11-30-49](https://user-images.githubusercontent.com/89828328/176374392-20341e09-1618-49fb-aeb3-10b9a474f495.png)
