### ISSUE TITLE
Using subscribtion as trigger function 

### ISSUE THREAD

**Issue by phappy** [FreeOpcUa/opcua-asyncio#485]
Hi @swamper123 ,
yes you are right, I have a general question and accidentally posted my topic here. I will create on the discussions board. Thanks

**Comment by swamper123** [comment]
@phappy I guess there is missing something. :^) 
But your topic sounds like a question in general, not a bug.

In case it is a bug, please use the template, to spare time asking for screenshots etc.
In case it is a question in gerneral, use [Discussions](https://github.com/FreeOpcUa/opcua-asyncio/discussions) board.
