### ISSUE TITLE
Client Subscription with Period 0 is broken

### ISSUE THREAD

**Issue by Koseng** [FreeOpcUa/opcua-asyncio#490]
@ZuZuD 
https://github.com/FreeOpcUa/opcua-asyncio/commit/ee844edb1038e0fff6684703e64b1530de5d534b broke client subscriptions with period 0.

`client.create_subscription(0, msclt)` leads to a ZeroDivision Exception.

That case needs to be handled in client.py in `def get_keepalive_count(self, period) -> int:`

> Exception has occurred: ZeroDivisionError       (note: full exception trace is shown but execution is paused at: _run_module_as_main)
> division by zero.
> 
> client.py", line 568, in get_keepalive_count
>     return int((self.session_timeout / period) * 0.75)

**Comment by ZuZuD** [comment]
This is pretty bad, let me fix this.
