### ISSUE TITLE
Wrong BrowseName with a string IdentifierType as NodeID

### ISSUE THREAD

**Issue by HermannSt** [FreeOpcUa/opcua-asyncio#518]
**Describe the bug** <br />
When I try to add a folder/object to my OPC-Server, with a string as IdentifierType, the BrowseName gets assigned the value 0, ignoring the NamespaceIndex number.

**To Reproduce**<br />
```
self.idx = await self.server.register_namespace(self.uri)
await self.server.get_objects_node().add_folder(self.idx, "Test")
await self.server.get_objects_node().add_folder(f"ns={self.idx};s=Test2", "Test2")
```

**Expected behavior**<br />
The BrowseName should have the NamespaceIndex number, not zero.

**Screenshots**<br />
UaExpert screenshots:
Test1 folder with ns=2 and BrowseName: 2, Test
![test1](https://user-images.githubusercontent.com/47702226/112861149-123dac00-90a4-11eb-894d-9ff4a046819a.png)

Test2 folder with ns=2 and BrowseName: 0, Test2
![Test2](https://user-images.githubusercontent.com/47702226/112861168-15d13300-90a4-11eb-939d-cab1201656df.png)

**Version**<br />
Python-Version: 3.8.3
opcua-asyncio Version: 0.9.14

**Comment by AndreasHeine** [comment]
https://github.com/FreeOpcUa/opcua-asyncio/blob/a5ac01707ee9a305f48b114c3e29cb02eecf49d2/asyncua/common/node.py#L669

second arg is bname (BrowseName)
```python
await self.server.get_objects_node().add_folder(f"ns={self.idx};s=Test2", f"{self.idx}:Test2")
```
