### ISSUE TITLE
#461 causing connection errors

### ISSUE THREAD

**Issue by swamper123** [FreeOpcUa/opcua-asyncio#520]
**Describe the bug** <br />
Since #461 Connection errors happen in UaExpert.

**To Reproduce**<br />
Run server-minimal.py and connect via UaExpert

**Expected behavior**<br />
No troubles should be caused while connecting.

**Screenshots**<br />
![grafik](https://user-images.githubusercontent.com/24408657/112956614-f1776400-9140-11eb-9cd3-60fe5c723fe2.png)

**Version**<br />
Python-Version: 3.8<br />
opcua-asyncio Version (e.g. master branch, 0.9): master

#461 should be reverted and fixed. @Koseng @oroulet

**Comment by oroulet** [comment]
Can you revert then? doing that was a bit of an issue anyway

**Comment by swamper123** [comment]
Couldn't push it on master on my own, so we have to do it via PR.

**Comment by Koseng** [comment]
Hi,
I basically just took that PR https://github.com/FreeOpcUa/python-opcua/pull/1197, which was recommended here: https://github.com/FreeOpcUa/python-opcua/issues/850 and did not do any further tests.

So we should check what is causing the trouble. I'll have a look.
