### ISSUE TITLE
MIT license

### ISSUE THREAD

**Issue by CSharpDummy** [FreeOpcUa/opcua-asyncio#531]
Any chance you could convert the license to MIT? For industrial applications MIT is a standard.

**Comment by AndreasHeine** [comment]
please use the discussions feature! --> https://github.com/FreeOpcUa/opcua-asyncio/discussions

**Comment by oroulet** [comment]
And I answer: No
Would need to fet everyone that has contributed to agree. It is never going to happen.
and also LGPL should be good engough for everything you want apart from copying the code inside your applicaiton
