### ISSUE TITLE
BadWriteNotSupported error

### ISSUE THREAD

**Issue by sdfzz** [FreeOpcUa/opcua-asyncio#536]
Hi all,

I'm trying to write an OPCUA client to control an OPCUA server (UA-7560M from ICP DAS), and got "BadWriteNotSupported: the server does not support writing the combination of value..." error.

Searching the forum here, I've found that this issue have been discussed a few times...but the proposed solutions did not work on my case:

dv = ua.DataValue(ua.Variant([True], ua.VariantType.Boolean))
dv.ServerTimestamp = datetime.now()
dv.SourceTimestamp = datetime.now()

or 

dv = ua.DataValue(ua.Variant([True], ua.VariantType.Boolean))
dv.ServerTimestamp = None
dv.SourceTimestamp = None

However, the OPCUA server works with the opcua-client, and checking the opcua-client, I've found that the server requires SourceTimestamp but not ServerTimestamp.

![opcua_client](https://user-images.githubusercontent.com/61696780/113700052-5159a600-9711-11eb-9f41-67479771714e.PNG)

So, I've tried:

dv = ua.DataValue(ua.Variant([True], ua.VariantType.Boolean))
dv.ServerTimestamp = None
dv.SourceTimestamp = datetime.now()

and got the same BadWriteNotSupported error...

One thing I've noticed from the opcua-client is that the timestamp format differs from what I've got by datetime.now():
opcua-client   : 2021-04-05T10:38:47:911768
datatime.now(): 2021-04-05 17:38:47:911768 (see the pic above)

Not sure where the letter "T" comes from, but I guess it is the cause of the error here. Does anyone know how to fix the problem, or how I can get the same timestamp as the opcua-client? 

Any help would be appreciated

Sincerely

Steve

**Comment by AndreasHeine** [comment]
why do you pass a list with just one item? if its scalar just pass "True"!

> use datetime.utcnow() 

all times are utc!!!

**Comment by sdfzz** [comment]
Thank you for the quick reply

Unfortunately, changing list nor using utcnow() solved the problem....still getting BadWriteNowSupported error...

**Comment by AndreasHeine** [comment]
which version of asyncua?

**Comment by AndreasHeine** [comment]
and please provide the full stacktrace!

**Comment by sdfzz** [comment]
Thank you for the response. I'm sorry but I've just left the lab....I will post update tomorrow.

Also, would you please tell me how I can check my asyncua version? I simply installed it with pip command.

**Comment by AndreasHeine** [comment]
https://pip.pypa.io/en/stable/reference/pip_list/

**Comment by sdfzz** [comment]
I'm so sorry, but the device is working now, although I didn't make any changes

Must have been a mistake in my code....I can control variables using:

dv = ua.DataValue(ua.Variant([True], ua.VariantType.Boolean))
dv.ServerTimestamp = None
dv.SourceTimestamp = None

I would like to close the issue. 

Thank you so much for your help
