### ISSUE TITLE
try and benchmark uvloop

### ISSUE THREAD

**Issue by oroulet** [FreeOpcUa/opcua-asyncio#54]
https://github.com/MagicStack/uvloop

@cbergmiller we should try it, especially on server it might help a lot

**Comment by oroulet** [comment]
Well I did some tests with one client and many may writes and the effect of using uvloop seems to be approximately ................. 0.0000..

**Comment by Ilyazyk** [comment]
uvloop does not support Windows at the moment
:(

**Comment by oroulet** [comment]
Anyway this is just an option it does not change anything in our code
