### ISSUE TITLE
memory leack in UaSocketProtocol

### ISSUE THREAD

**Issue by oroulet** [FreeOpcUa/opcua-asyncio#55]
_callbackmap is never emptied! it might be possible to simply remove objects after a callback is used, but isnt'it any cases where _callbackmap is reused? I am thinking at subscriptions for examples.... @cbergmiller

**Comment by cbergmiller** [comment]
That is indeed a flaw. I checked and `_callbackmap` is not used outside of the `UASocketProtocol`.
It may be enough to delete the mat item in `_call_callback` after setting the future result.
In case a request is not answered by the server the callback would never be deleted - not sure if this case needs to be handled too.

**Comment by oroulet** [comment]
ok pushed it. let's see how it works...
