### ISSUE TITLE
How to set method after server importing xml?

### ISSUE THREAD

**Issue by LuckyHouse** [FreeOpcUa/opcua-asyncio#566]
![image](https://user-images.githubusercontent.com/19794322/117943533-d2264600-b33e-11eb-8562-be0d0ac1385a.png)

Hello, i'm new to OPCUA. 
My xml contains method nodes. It seems normal after importing 
But when i call the method UpdateCameras， the error message shown above is displayed.
Is there a way to reset the method of one node?

**Comment by AndreasHeine** [comment]
"assuming you are the ua server"
is the method bound to a callback (python-function)?
