### ISSUE TITLE
Subscribe to CODESYS OPC UA events not working

### ISSUE THREAD

**Issue by mozesa** [FreeOpcUa/opcua-asyncio#573]
**Describe the bug** <br />
OPC UA events subscription does not work.
I enclosed a picture in which it is clearly visible that `evfilter.SelectClauses` elements' `TypeDefinitionId` == `NodeId(Identifier=0, NamespaceIndex=0, NodeIdType=<NodeIdType.TwoByte: 0>)`.

It should be `NodeId(Identifier=2041, NamespaceIndex=0, NodeIdType=<NodeIdType.TwoByte: 0>)`.

**To Reproduce**<br />
```python
import asyncio

from asyncua import Client


class SubscriptionHandler:
    def event_notification(self, event):
        print(f"{event=}")


async def main():
    client = Client(url="opc.tcp://127.0.0.1:4840/")
    async with client:
        handler = SubscriptionHandler()
        sub = await client.create_subscription(500, handler)
        handle = await sub.subscribe_events()
        await asyncio.sleep(60)
        await sub.unsubscribe(handle)
        await sub.delete()


if __name__ == "__main__":
    asyncio.run(main())
```

**Expected behavior**<br />
Proper behavior of `get_filter_from_event_type`.

**Screenshots**<br />
![image](https://user-images.githubusercontent.com/49973426/118867190-15565b00-b8e3-11eb-9b63-84417b1f6632.png)

**Version**<br />
Python-Version: 3.9.5
opcua-asyncio version: master branch

There is a [discussion](https://github.com/FreeOpcUa/opcua-asyncio/discussions/572) too.

**Comment by mozesa** [comment]
The problem comes from the not proper `get_filter_from_event_type` function.
The event type is `i=2782`, but the function creates a filter for `i=0`.

![image](https://user-images.githubusercontent.com/49973426/119114257-48edce00-ba26-11eb-9ba1-7779325b562b.png)

**Comment by mozesa** [comment]
Am I right or I miss something?
Currently I use a monkey patch to overcome this issue.

How can I help you solving this issue?

Thanks for your help in advance.

**Comment by mozesa** [comment]
I created an overview - you can reach it [here](https://github.com/FreeOpcUa/opcua-asyncio/discussions/572#discussioncomment-796555)

**Comment by oroulet** [comment]
Can you make a PR of your patch? Looks like you known better than everyone here what the correct behaviour is. I do not use events currently so I do not remember much

**Comment by mozesa** [comment]
Unfortunately I couldn't patch it properly.
It would require more thorough examination of the event's implementation itself - the problem is buried there.

What I have described is still valid.

(Currently I am coding in Golang so no Python on the horizon.)
