### ISSUE TITLE
Question: Client, production ready?

### ISSUE THREAD

**Issue by mariopoeta** [FreeOpcUa/opcua-asyncio#58]
Hi,

Do you guys think that the client is production ready? :)

**Comment by oroulet** [comment]
nobody knows... I am sure it is not worse than some creepy software that people write or use in production everyday but nobody will do support for you so you need to be able to debug it.
I do not think we have any known bugs in client but not so many people use it yet

**Comment by mariopoeta** [comment]
I am looking to use the client with AWS Greengrass since now supports python3.7.

I am struggling with the opcua nodejs :)

**Comment by oroulet** [comment]
Nodejs has been here a long time. What kind of issues do you have?

**Comment by mariopoeta** [comment]
Example, the issue that i am currently troubleshooting.

                const payload = {
                    id: nodeId,
                    value: dataValue.value,
                    timestamp: dataValue.sourceTimestamp,
                };

i want the sourceTimestamp, but i am getting the default value null. but i am able to see sourceTimestamp through quick client or uaexpert.

**Comment by oroulet** [comment]
I think which timestamp is sent is an option in a read request
