### ISSUE TITLE
Next planned release?

### ISSUE THREAD

**Issue by peteryin21** [FreeOpcUa/opcua-asyncio#64]
Hi, I am in the process of converting our codebase from `python-opcua`, and we rely on a feature to be able to pass in an event loop into the server from [this commit](https://github.com/FreeOpcUa/opcua-asyncio/commit/56cf68dfc51cb80418ed7a94e6b84edac2ffaabe#diff-85f90aee7fd78d5c077634c3b26eb9bd). 

I noticed this is not in 0.5.0. When is the next planned release?

**Comment by oroulet** [comment]
OK made a release just now since we have a few bigger changes in the pipeline

**Comment by peteryin21** [comment]
@oroulet Thanks! For future reference, is there a forum/email chain where new features and releases are discussed?

**Comment by oroulet** [comment]
We just discuss things in pull requests and bug reports.
