### ISSUE TITLE
Struct typedefinition is wrong

### ISSUE THREAD

**Issue by SArzbach** [FreeOpcUa/opcua-asyncio#642]
I'm running a OPC-UA server on an Omron NX102-9000.
Im using structs to combine variables.
The library doesn't return the Typeinformation and the ID of the type node is off by one.
When im using load_type_definitions() i'm getting an Exception.
get_value() is running, but returns a wrong Datatype

```python
print(await systeminfo.get_value())
```

the dataFEED client can read the Typeinformation just fine:
![Datafeed_Var](https://user-images.githubusercontent.com/88654334/128682465-50f10f4a-0059-4adb-8a9d-13ab07375b4b.PNG)

get value returns the correct content, but the Type is wrong and the type ID is the correct type ID plus one
![Complete](https://user-images.githubusercontent.com/88654334/128681959-2e9afca4-51dc-4dae-b4e0-eaa8a555bdf1.PNG)

```python
print(await self.client.client.load_type_definitions([systeminfo]))
```

The load_type_definitions function runs into an exception:
![Exception](https://user-images.githubusercontent.com/88654334/128682808-7d56157c-8534-4b6e-8067-f86c5ac6d50e.PNG)

Versions:
Python-Version: 3.9
opcua-asyncio Version: 0.9.90

**Comment by AndreasHeine** [comment]
have you tried load_data_type_definitions ?

https://github.com/FreeOpcUa/opcua-asyncio/blob/085b00e41e98a33230f735d25597007a8b5f099d/asyncua/client/client.py#L664

**Comment by SArzbach** [comment]
> 
> 
> have you tried load_data_type_definitions ?
> 
> https://github.com/FreeOpcUa/opcua-asyncio/blob/085b00e41e98a33230f735d25597007a8b5f099d/asyncua/client/client.py#L664

now i have 
it just returns an empty dictionary without a specified node as well as with the node in question as variable
the return of the get_value call also remains the same

**Comment by oroulet** [comment]
I am impressed how few servers support the 1.04 specification.... you should check with omron if the ua server on PLc can be updated. 1.04 really clean up the custom struct implementation. (load_data_type_definition() uses the new protocol, load_type_definition the old one, which imports an xml in the background)

**Comment by oroulet** [comment]
if there is an offsett, then someone introduced a bug in xml importer in that case. when importing xml from server, we should not migrate the namespaces, they are already correct

**Comment by SArzbach** [comment]
Update: 
```python
systeminfo.read_data_type()
```
Does return the correct TypeId, NodeId

**Comment by SArzbach** [comment]
@oroulet the highest opc-ua version possible would be 1.03

**Comment by AndreasHeine** [comment]
it would be interesting if the issue is also in python-opcua!?
https://github.com/FreeOpcUa/python-opcua

**Comment by oroulet** [comment]
obs sorry I did not read carefully the bug description. looks like you are passing the wrong node to load_type_definition(). The value of the nodes should be xml text, you are obvisouly passing a node having some extension object. What happens when you run load_type_definition() wihtout argument. Doesn't it work?

**Comment by SArzbach** [comment]
> 
> 
> obs sorry I did not read carefully the bug description. looks like you are passing the wrong node to load_type_definition(). The value of the nodes should be xml text, you are obvisouly passing a node having some extension object. What happens when you run load_type_definition() wihtout argument. Doesn't it work?

Thank you that solved it.
