### ISSUE TITLE
create_object(nodeid, bname, objecttype=nodeid),  the Modeling rules of Child node are missing

### ISSUE THREAD

**Issue by 1014095456** [FreeOpcUa/opcua-asyncio#653]
# create a new object type1
    mycustomobj_type = await server.nodes.base_object_type.add_object_type(idx, "MyCustomObjectType")
    var = await mycustomobj_type.add_variable(0, "var_should_be_there_after_instantiate", 1.0)
    await var.set_modelling_rule(True)
    mycustomobj_nodeid = (await server.nodes.base_object_type.get_child([f"{idx}:MyCustomObjectType"])).nodeid

    # create another object type use object type1 as child
    obj_type = await server.nodes.base_object_type.add_object_type(idx, "OtherCustomobj_type")
    chdobj = await obj_type.add_object(idx, "MyCustomObjectB",mycustomobj_nodeid)
    await chdobj.set_modelling_rule(True)

    # instantiate
    MYobj1 = await instantiate(server.nodes.objects, obj_type, bname="2:model0001")

if instantiate the 'obj_type', the child of 'chdobj' will not be instantiate,such as 'var',unless define the modeling rules of ‘var’ again.

**Comment by luchp** [comment]
That is unfortunate, even if it is compliant to opc ua spec.

**Comment by luchp** [comment]
Would it not be possible to have an option to restore the modelling rule when adding an object to an object_type with instantiate
