### ISSUE TITLE
AttributeError: module 'asyncua.ua' has no attribute 'NX__sSOCKET_ADDRESS'

### ISSUE THREAD

**Issue by cbudai** [FreeOpcUa/opcua-asyncio#670]
When I try to load the types and custom structures from the OPC  

```
        async with Client(url='opc.tcp://192.168.250.1:4840') as client:
            await client.connect()
            await client.load_type_definitions()

```
I have the following exception:

@dataclass
class NX__sSOCKET:

    '''
    NX__sSOCKET structure autogenerated from xml
    '''

    Handle:ua.UInt32 = 0
    SrcAdr:ua.NX__sSOCKET_ADDRESS = ua.NX__sSOCKET_ADDRESS()
    DstAdr:ua.NX__sSOCKET_ADDRESS = ua.NX__sSOCKET_ADDRESS()

ERROR:asyncua.common.structures:Failed to execute auto-generated code from UA datatype: 

@dataclass
class NX__sSOCKET:

    '''
    NX__sSOCKET structure autogenerated from xml
    '''

    Handle:ua.UInt32 = 0
    SrcAdr:ua.NX__sSOCKET_ADDRESS = ua.NX__sSOCKET_ADDRESS()
    DstAdr:ua.NX__sSOCKET_ADDRESS = ua.NX__sSOCKET_ADDRESS()
Traceback (most recent call last):
  File "C:\Users\cbudai\AppData\Local\Programs\Python\Python39\lib\site-packages\asyncua\common\structures.py", line 281, in _generate_python_class
    exec(code, env)
  File "<string>", line 4, in <module>
  File "<string>", line 11, in NX__sSOCKET
AttributeError: module 'asyncua.ua' has no attribute 'NX__sSOCKET_ADDRESS'

**Comment by swamper123** [comment]
Have you tried `load_data_type_definitions()` instead of `load_type_definitions()` ? Because it may be deprecated.
