### ISSUE TITLE
new version of asyncua produces BadDecodingError when any variable is read from asyncua server

### ISSUE THREAD

**Issue by thunderbug1** [FreeOpcUa/opcua-asyncio#729]
After upgrading I encountered an issue where ua expert gets BadDecodingError when reading any variable from the asyncua server (folders work fine).
This did not happen with an older version of asyncua.
Here are screenshots of ua expert 

asyncua==0.9.14    
![image](https://user-images.githubusercontent.com/1395321/142451521-7d06318f-4ee2-4f44-93a2-0c2dba3f9777.png)

asyncua==0.9.91 (exact same code as before)
![image](https://user-images.githubusercontent.com/1395321/142450676-fd78ac88-f41c-42fe-bc1b-e903bded75ec.png)

everything was run with Python 3.8.10

I didn't have time to build a minimal example yet.

**Comment by oroulet** [comment]
What kind of server?

**Comment by oroulet** [comment]
I tested all kind of possible variables with asyncua server and uaexpert and prosys client as client and everything seems fine. must be something special with your setup. or something here that makes it work

**Comment by oroulet** [comment]
last asyncua version is 0.9.92, try to upgrade first. I thing there was a bad bug in 0.9.91

**Comment by thunderbug1** [comment]
@oroulet oh yes thank you, with the version 0.9.92 the bug seems to be gone.
