### ISSUE TITLE
Syntax Error: Client examples

### ISSUE THREAD

**Issue by MGGEL** [FreeOpcUa/opcua-asyncio#73]
I've installed Python 3.7 and 3.6 but I'm not able to run the example client code from the documentation.
```
from asyncua import Client

async with Client(url='opc.tcp://172.16.3.51:4840/freeopcua/server/') as client:
    while True:
        # Do something with client
        node = client.get_node('i=85')
        value = await node.get_value()
```
The Error message for Python 3.7:
```
  File "test.py", line 3
    async with Client(url='opc.tcp://172.16.3.51:4840/freeopcua/server/') as client:
    ^
SyntaxError: 'async with' outside async function
```
The Error message for Python3.6:

```
  File "test.py", line 3
    async with Client(url='opc.tcp://172.16.3.51:4840/freeopcua/server/') as client:
             ^
SyntaxError: invalid syntax
```

Is the documentation outdated or am I doing something wrong?

**Comment by cbergmiller** [comment]
Sorry for the unclear documentation, have a look at this example:
https://github.com/FreeOpcUa/opcua-asyncio/blob/master/examples/client-minimal.py
You have to put `async with` inside of a async function and run it as an task.
