### ISSUE TITLE
Missing await in server.link_method

### ISSUE THREAD

**Issue by jenrei** [FreeOpcUa/opcua-asyncio#74]
I get `RuntimeWarning: coroutine 'InternalSession.add_method_callback' was never awaited` message when using the link_method() function of server.py
This works for me:

async def link_method(self, node, callback):
        """
        Link a python function to a UA method in the address space; required when a UA method has been imported
        to the address space via XML; the python executable must be linked manually
        :param node: UA method node
        :param callback: python function that the UA method will call
        """
        await self.iserver.isession.add_method_callback(node.nodeid, callback)

**Comment by cbergmiller** [comment]
Thanks for reporting this issue!
