### ISSUE TITLE
should use await for connect or not? how to connect from __init__?

### ISSUE THREAD

**Issue by ronytesler** [FreeOpcUa/opcua-asyncio#762]
why doesn't the file client_to_prosys_cert.py use await?

I want to connect the server when my module loads, so I want to call connect in __init__. But it's not possible to call await from init. What should I do?

**Comment by oroulet** [comment]
`__init__()` is not async . the usual way to bypass that issue is to add a method `init()`to your class that is async. I think InternalServer in asyncua does that. t

**Comment by ronytesler** [comment]
@oroulet What does this code from client_to_prosys_cert.py work without calling await?
        ```
        client.connect()
        root = client.nodes.root
        objects = client.nodes.objects
        print("childs og objects are: ", objects.get_children())
```

**Comment by oroulet** [comment]
it does not work. Looks like that file has never been ported since fork from python-opcua

**Comment by oroulet** [comment]
look at client_to_prosys.py. it is correct

**Comment by ronytesler** [comment]
ah great, thanks.
so asyncio.run(main()) is the way to call an async function from `__init__`?

**Comment by oroulet** [comment]
asyncio.run(main()) is the entry point of you entire async programm. there is not `__init__` in that case. It is a function

**Comment by ronytesler** [comment]
Right. But is calling asyncio.run(main()) from `__init__` (in my own package where I do have it) the same as calling it from outside a function?

**Comment by oroulet** [comment]
Never call Asuncio.run() from anywhere else than a python main entry file. Read an async tutorial
