### ISSUE TITLE
Server refresh rate

### ISSUE THREAD

**Issue by om327** [FreeOpcUa/opcua-asyncio#789]
Hello, 

IS there a way to set the update interval in the server? 

There seems to be a long refresh lag when subscribing to nodes from NodeJS and UAExpert. My opcua-asyncio server is polling my device every 250ms and prints out the new value in the terminal before it passes it to the server. However, the server only seems to update once every 5 seonds even though i see multiple print outs?

I know in other lanugaues implimentations you can define the server refresh rate - is there an option in opcua-asyncio?

Many thanks!
Ollie

**Comment by AndreasHeine** [comment]
there is no server refreshrate! there are some parameters you can set from client side like publishinterval and samplinginterval but to be published the value or statuscode must change.

Subscription:
https://reference.opcfoundation.org/v104/Core/docs/Part4/5.13.1/

MonitoredItems:
https://reference.opcfoundation.org/v104/Core/docs/Part4/5.12.1/

can you provide a simplified code example?

**Comment by AndreasHeine** [comment]
how long does `pressures = R2R4.get_pressures()` takes?

**Comment by om327** [comment]
< 25ms - i'm new to async and python in general so i'll have a play with the async wait times adn see if that helps. I'll also play around with the settings in NodeJS. It migth be something very simple i'm missing. On a side note when polling like this and where you want to invoke methods or updat enodes from the client side that triger functions is it best to use queues for everything? Statemachines? or simple have a simple while loop like above and let the methods trigger without any further handelling?

**Comment by AndreasHeine** [comment]
if the problem still exist reopen!
