### ISSUE TITLE
ERROR: subscribing to nodes on server side (subscribe_data_change)

### ISSUE THREAD

**Issue by om327** [FreeOpcUa/opcua-asyncio#795]
Hello, I'm trying to use the subcribe_data_change function to trigger functions on the server side when a node is changed. I can get the example to work in the orginal python-opcua library but it doesn't seem to work in the asynicua library? 

When i run the example or my own i get the following error:
```python 
INFO:asyncua.server.internal_session:close session Internal
INFO:asyncua.server.subscription_service:delete subscriptions: []
Traceback (most recent call last):

    handle = sub.subscribe_data_change(myvar)
AttributeError: 'coroutine' object has no attribute 'subscribe_data_change'
sys:1: RuntimeWarning: coroutine 'Server.create_subscription' was never awaited
```
Is this no longer supported or is there a better way to trigger fucntions on the server side when a ndoe changes value from a client?

Many thanks!
Ollie

**Comment by om327** [comment]
Is it best practise not to have funcions triggered on node-changes written to by a client? Is it better to only use methods?

**Comment by AndreasHeine** [comment]
> Hello, I'm trying to use the subcribe_data_change function to trigger functions on the server side when a node is changed. I can get the example to work in the orginal python-opcua library but it doesn't seem to work in the asynicua library?
> 
> When i run the example or my own i get the following error:
> 
> INFO:asyncua.server.internal_session:close session Internal
> INFO:asyncua.server.subscription_service:delete subscriptions: []
> Traceback (most recent call last):
> 
> handle = sub.subscribe_data_change(myvar)
> 
> AttributeError: 'coroutine' object has no attribute 'subscribe_data_change'
> sys:1: RuntimeWarning: coroutine 'Server.create_subscription' was never awaited
> 
> Is this no longer supported or is there a better way to trigger fucntions on the server side when a ndoe changes value from a client?
> 
> Many thanks!
> Ollie

```python
handle = await sub.subscribe_data_change(myvar)
```

e.g.:
https://github.com/AndreasHeine/opcua-tutorial/blob/main/client/subscribe.py

**Comment by swamper123** [comment]
`subscribe_data_change` is a Coroutine in this repo and has to be awaited.

[See our example](https://github.com/FreeOpcUa/opcua-asyncio/blob/84b4a60f39c9d71e4c22b9c036611783d03de13d/examples/client-subscription.py)

**Comment by om327** [comment]
Thanks for the quick reply - its ther server side not client. I've tried to eddit the code but it looks like the subscribe_data_chnage fucntion no longer exists in the server as VS doesn't have any intelisense for this method unlike the others?

    async with server:

        handler = SubHandler()
        subscription  = server.create_subscription(250, handler)
        
        nodes = [R2_system_status_node, R2_pump_A_status_node,
        R2_pump_B_status_node, R2_pump_A_setpoint_node,
        R2_pump_B_setpoint_node, R2_valve_A_status_node, 
        R2_valve_B_status_node, R2_valve_C_status_node,
        R2_sample_loop_A_status_node, R2_sample_loop_B_status_node, 
        R4_reactor_A_setpoint_node, R4_reactor_B_setpoint_node, 
        R4_reactor_C_setpoint_node, R4_reactor_D_setpoint_node]

        await subscription.subscribe_data_change(nodes)

ERROR: AttributeError: 'coroutine' object has no attribute 'subscribe_data_change'
sys:1: RuntimeWarning: coroutine 'Server.create_subscription' was never awaited

**Comment by om327** [comment]
i've updated the code in repo example for the server with the await and the example also doesn't work?

**Comment by AndreasHeine** [comment]
https://github.com/AndreasHeine/opcua-tutorial/blob/5fff655b9e286707b0def15eb2d70619266332f3/client/subscribe.py#L44

and on serverside sub:

`subscription  = await server.create_subscription(250, handler)`

**Comment by om327** [comment]
i'm using the repo example:

import asyncio
import copy
import logging
from datetime import datetime
import time
from math import sin


from asyncua import ua, uamethod, Server


class SubHandler(object):

    """
    Subscription Handler. To receive events from server for a subscription
    """

    def datachange_notification(self, node, val, data):
        print("Python: New data change event", node, val)

    def event_notification(self, event):
        print("Python: New event", event)


# method to be exposed through server

def func(parent, variant):
    ret = False
    if variant.Value % 2 == 0:
        ret = True
    return [ua.Variant(ret, ua.VariantType.Boolean)]


# method to be exposed through server
# uses a decorator to automatically convert to and from variants

@uamethod
def multiply(parent, x, y):
    print("multiply method call with parameters: ", x, y)
    return x * y


async def main():
    # optional: setup logging
    #logger = logging.getLogger("asyncua.address_space")
    # logger.setLevel(logging.DEBUG)
    #logger = logging.getLogger("asyncua.internal_server")
    # logger.setLevel(logging.DEBUG)
    #logger = logging.getLogger("asyncua.binary_server_asyncio")
    # logger.setLevel(logging.DEBUG)
    #logger = logging.getLogger("asyncua.uaprocessor")
    # logger.setLevel(logging.DEBUG)

    # now setup our server
    server = Server()
    await server.init()
    server.disable_clock()  #for debuging
    #server.set_endpoint("opc.tcp://localhost:4840/freeopcua/server/")
    server.set_endpoint("opc.tcp://0.0.0.0:4840/freeopcua/server/")
    server.set_server_name("FreeOpcUa Example Server")
    # set all possible endpoint policies for clients to connect through
    server.set_security_policy([
                ua.SecurityPolicyType.NoSecurity,
                ua.SecurityPolicyType.Basic256Sha256_SignAndEncrypt,
                ua.SecurityPolicyType.Basic256Sha256_Sign])

    # setup our own namespace
    uri = "http://examples.freeopcua.github.io"
    idx = await server.register_namespace(uri)

    # create a new node type we can instantiate in our address space
    dev = await server.nodes.base_object_type.add_object_type(idx, "MyDevice")
    await (await dev.add_variable(idx, "sensor1", 1.0)).set_modelling_rule(True)
    await (await dev.add_property(idx, "device_id", "0340")).set_modelling_rule(True)
    ctrl = await dev.add_object(idx, "controller")
    await ctrl.set_modelling_rule(True)
    await (await ctrl.add_property(idx, "state", "Idle")).set_modelling_rule(True)

    # populating our address space

    # First a folder to organise our nodes
    myfolder = await server.nodes.objects.add_folder(idx, "myEmptyFolder")
    # instanciate one instance of our device
    mydevice = await server.nodes.objects.add_object(idx, "Device0001", dev)
    mydevice_var = await mydevice.get_child([f"{idx}:controller", f"{idx}:state"])  # get proxy to our device state variable
    # create directly some objects and variables
    myobj = await server.nodes.objects.add_object(idx, "MyObject")
    myvar = await myobj.add_variable(idx, "MyVariable", 6.7)
    await myvar.set_writable()    # Set MyVariable to be writable by clients
    mystringvar = await myobj.add_variable(idx, "MyStringVariable", "Really nice string")
    await mystringvar.set_writable()    # Set MyVariable to be writable by clients
    mydtvar = await myobj.add_variable(idx, "MyDateTimeVar", datetime.utcnow())
    await mydtvar.set_writable()    # Set MyVariable to be writable by clients
    myarrayvar = await myobj.add_variable(idx, "myarrayvar", [6.7, 7.9])
    myuintvar = await myobj.add_variable(idx, "myuintvar", ua.UInt16(4))
    await myobj.add_variable(idx, "myStronglytTypedVariable", ua.Variant([], ua.VariantType.UInt32))
    await myarrayvar.set_writable(True)
    myprop = await myobj.add_property(idx, "myproperty", "I am a property")
    mymethod = await myobj.add_method(idx, "mymethod", func, [ua.VariantType.Int64], [ua.VariantType.Boolean])
    multiply_node = await myobj.add_method(idx, "multiply", multiply, [ua.VariantType.Int64, ua.VariantType.Int64], [ua.VariantType.Int64])

    # import some nodes from xml
    #await server.import_xml("custom_nodes.xml")

    # creating a default event object
    # The event object automatically will have members for all events properties
    # you probably want to create a custom event type, see other examples
    myevgen = await server.get_event_generator()
    myevgen.event.Severity = 300

    # starting!
    async with server:
        print("Available loggers are: ", logging.Logger.manager.loggerDict.keys())
        # enable following if you want to subscribe to nodes on server side
        handler = SubHandler()
        sub = server.create_subscription(500, handler)
        handle = sub.subscribe_data_change(myvar)
        # trigger event, all subscribed clients wil receive it
        var = await myarrayvar.read_value()  # return a ref to value in db server side! not a copy!
        var = copy.copy(var)  # WARNING: we need to copy before writting again otherwise no data change event will be generated
        var.append(9.3)
        await myarrayvar.write_value(var)
        await mydevice_var.write_value("Running")
        await myevgen.trigger(message="This is BaseEvent")
        await server.write_attribute_value(myvar.nodeid, ua.DataValue(0.9))  # Server side write method which is a bit faster than using write_value
        while True:
            await asyncio.sleep(0.1)
            await server.write_attribute_value(myvar.nodeid, ua.DataValue(sin(time.time())))


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    asyncio.run(main())

**Comment by AndreasHeine** [comment]
could you pleas format your codeblock!

![image](https://user-images.githubusercontent.com/56362817/153859189-fc7b3c52-a217-48c3-a419-b600b0db22a6.png)

**Comment by om327** [comment]
Sorry I'm new to this and didn't realise this would formst the codfe like that - it took this directly from the examples

https://github.com/FreeOpcUa/opcua-asyncio/blob/master/examples/server-example.py

i uncommeted the lines i thought i needed but looks like they're missing the awaits - i'm still getting my head around async so sorry if its daft question :)

Adding the await has done thr trick though! Thank You!

**Comment by AndreasHeine** [comment]
> Sorry I'm new to this and didn't realise this would format the code like that - it took this directly from the examples
> 
> https://github.com/FreeOpcUa/opcua-asyncio/blob/master/examples/server-example.py
> 
> i uncommeted the lines i thought i needed but looks like they're missing the awaits - i'm still getting my head around async so sorry if its daft question :)
> 
> Adding the await has done the trick though! Thank You!

my post above looks like theis in markdown:
![image](https://user-images.githubusercontent.com/56362817/153859891-e3477b2c-3a6a-4cce-8ea9-5b9532520d3c.png)

**Comment by om327** [comment]
i've tried adding that to my previous code in the comments '''python <code > ''' but that doens't do anything?

**Comment by AndreasHeine** [comment]
https://github.com/FreeOpcUa/opcua-asyncio/pull/796

looks like old stuff from python-opcua port to asyncio...

**Comment by AndreasHeine** [comment]
but anyways you need to put an `await` in front of a coroutine (async function) otherwise it will not run!

**Comment by AndreasHeine** [comment]
you need to use ` and not ' or "

**Comment by AndreasHeine** [comment]
and if you write python or js or ... it makes the correct language highlighting
![image](https://user-images.githubusercontent.com/56362817/153864425-7da46ad8-46a4-487e-b963-b2963b8e41d3.png)

**Comment by AndreasHeine** [comment]
looks more readable now ;)

as mentioned it should work if you add the awaits!
https://github.com/FreeOpcUa/opcua-asyncio/pull/796/files

**Comment by AndreasHeine** [comment]
if the problem still exist reopen!
