### ISSUE TITLE
asyncua module not loaded

### ISSUE THREAD

**Issue by dudanisu** [FreeOpcUa/opcua-asyncio#81]
I downloaded asyncua, however when I Debug the code the message "Exception has occurred: ModuleNotFoundError" pops up. If I do pip3 list, I can see asyncua  0.5.1 has been loaded.

**Comment by cbergmiller** [comment]
Hello! We need more information to help you. Please post the relevant part of your code and the full Exception message.

**Comment by swamper123** [comment]
Since this is more than a year old, without further description, I guess this can be closed.
