### ISSUE TITLE
Certificate handling

### ISSUE THREAD

**Issue by mitchpi** [FreeOpcUa/opcua-asyncio#82]
Hi Guys, thanks for a great package!

I'm struggling a little with the certificate handling. The server always accepts self signed certificates, shouldn't the certificates have to be moved to a trust list prior to it being trusted? And hence the client will be rejected and not able to view the server nodes?

Cheers. Mitch.

**Comment by oroulet** [comment]
It should... Patch welcome ;-)

**Comment by mitchpi** [comment]
Thanks for the prompt response! I'll investigate, may be a bit beyond me.

**Comment by JoeyFaulkner** [comment]
Hi there! 

also echo mitchpi's sentiment: this is an awesome package! I would like to work on this certificate handling. Do you have any tips on where this needs to be implemented and if there's anything I need to be careful of?

**Comment by JoeyFaulkner** [comment]
@oroulet i think we can close this issue now because of the closed PR?
