### ISSUE TITLE
Can we move pytest-runner requirement to tests_require instead of setup_requires?

### ISSUE THREAD

**Issue by memetb** [FreeOpcUa/opcua-asyncio#86]
Title is pretty explanatory: current setup script [requires](https://github.com/FreeOpcUa/opcua-asyncio/blob/08861799d3413345dcc5b4ae387427739b864bad/setup.py#L38) `pytest-runner` on installation. But this requirement is only true if you want to run tests and is an unnecessary burden on production devices.

PR would be trivial. I can immediately submit it or let team handle. 

Thanks.

**Comment by oroulet** [comment]
Good point. Best if you do it, there is no real team just people writing code when they have to.. Generally for that kind of thing it is even better to make PR directly instead of opening bug ;-)

**Comment by memetb** [comment]
Ok, sorry if I hadn't done this before, but I just saw this as I was editing for a PR: the `asyncio` branch actually already has this issue properly solved (but the `master` branch doesn't).

I was assuming I'd not be PR'ing directly against master, which is why I looked at asyncio.

Advice?

**Comment by oroulet** [comment]
I do not follow your reasoning here. There is no asyncio branch. You should make a PR against master for opcua-asyncio

**Comment by memetb** [comment]
Sorry, I was unclear, the branch is asyncua: [see here](https://github.com/FreeOpcUa/opcua-asyncio/blob/7d3d31ba20ccf484341245757a1c7546a9e9ccae/setup.py#L12)

In any case, I will make the PR against master. You can reject it if it's easier to merge asyncua.
