### ISSUE TITLE
Attribute Error in struct_to_binary with LocalizedText

### ISSUE THREAD

**Issue by Nanahara** [FreeOpcUa/opcua-asyncio#87]
Hello,
In `struct_to_binary` function an AttributeError is throw with LocalizedText object that are initialized like this in standard_address_space files:

`ua.Variant([('Locale', 'en'), ('Text', 'Inactive')], ua.VariantType.LocalizedText)`

When I use the same way used on python-opcua it work fine: 

`ua.Variant(LocalizedText("Inactive"), ua.VariantType.LocalizedText)`

**Comment by schroeder-** [comment]
Behaviour changed with this lib.
