### ISSUE TITLE
Unable to connect to new server using Aes128_Sha256_RsaOaep

### ISSUE THREAD

**Issue by jfrechard** [FreeOpcUa/opcua-asyncio#874]
**Problem ** <br />

I am trying to connect to a new generation OPC UA server.
Connexion works fine with uaExpert with these parameters : 

![image](https://user-images.githubusercontent.com/75083406/166462257-ac797f67-054d-4471-85fd-28d0f04582ab.png)

However, using asyncua I obtain : 

`asyncua.ua.uaerrors._base.UaError: Unsupported security policy http://opcfoundation.org/UA/SecurityPolicy#Aes128_Sha256_RsaOaep`

My code that work with another server : 
```
async def task():
    url = influx.machine_cfg.opc_url 
    client = Client(url=url)
    client.set_user("toto")#influx.machine_cfg.opc_user)
    client.set_password("toto")#influx.machine_cfg.opc_password)
    #print(url,influx.machine_cfg.opc_user,influx.machine_cfg.opc_password,opc.cert,opc.private_key)
    await client.set_security(
        SecurityPolicyBasic256Sha256,
        certificate=opc.cert,
        private_key=opc.private_key
    )
    async with client:
        handler = opc.SubscriptionHandler()
        subscription = await client.create_subscription(100, handler)
        nodes = []
        for node in list_var_nodes:
            nodes.append(client.get_node(node))
        print(nodes)
        # We subscribe to data changes for two nodes (variables).
        await subscription.subscribe_data_change(nodes)
        # We let the subscription run for ten seconds
        await asyncio.sleep(3600000)
        # We delete the subscription (this un-subscribes from the data changes of the two variables).
        # This is optional since closing the connection will also delete all subscriptions.
        await subscription.delete()
        # After one second we exit the Client context manager - this will close the connection.
        await asyncio.sleep(1)
```

**Comment by AndreasHeine** [comment]
you don't use the correct security policy!?

not sure what this is -> "SecurityPolicyBasic256Sha256" (DataType?)

**Comment by jfrechard** [comment]
I use it like example shows : 

'from asyncua.crypto.security_policies import SecurityPolicyBasic256Sha256'

**Comment by AndreasHeine** [comment]
how did you generate your cert?

**Comment by jfrechard** [comment]
Using openSSL. 
My client works on another server (different hardware).

**Comment by AndreasHeine** [comment]
weird!

the error happens here:
https://github.com/FreeOpcUa/opcua-asyncio/blob/259811d5ad11c47c8d2b2289a8a2783b97c79421/asyncua/crypto/security_policies.py#L705

but we dont support the "Aes128_Sha256_RsaOaep" policy only SecurityPolicyBasic256Sha256, SecurityPolicyBasic256, SecurityPolicyBasic128Rsa15

**Comment by jfrechard** [comment]
Ok, 
I thought that the server support all policies and we can choose one of them.

If I remove user and password, it works ...

**Comment by jfrechard** [comment]
Thanks a lot !

**Comment by AndreasHeine** [comment]
:astonished:

**Comment by jfrechard** [comment]
? 
why are you astonished? because of my thought ? because I said "thanks' ?

**Comment by AndreasHeine** [comment]
> If I remove user and password, it works ...

!?

**Comment by jfrechard** [comment]
yes for sure.
I have an access to a simple web interface to configure the OPCUA server of my device, if I remove user and password of this configuration and if I remove it in my code it works.




I change nothing except that in my code 
'''
    client.set_user("")
    client.set_password("")
'''

I think the manufacturer of the device said that if you let user and password blank in the server configuration, it will start the server without encryption...

**Comment by AndreasHeine** [comment]
what server/vendor is it? (for my own curiosity ^^)

**Comment by jfrechard** [comment]
Its an HMA box from Siemens.

Its a computer running windows 10 IoT, you plug it on an hold Siemens CNC and he will expose variables you choose using OPCUA.

Its a simple way to add an OPC UA server to an old CNC without OPC capability.
