### ISSUE TITLE
`new_struct(..., is_union=True)` is not working as expected

### ISSUE THREAD

**Issue by danmoser** [FreeOpcUa/opcua-asyncio#875]
**Describe the bug** <br />
I've created a custom struct with `asyncua.common.structures104.new_struct()` and tried to convert it to "Union". Then the `.read_value()` from the nodeset is empty. If disable keep it as a regular struct (ie., `is_union=False`) it works good.

**Screenshots**<br />
`is_union=False`:
![struct_unionFalse](https://user-images.githubusercontent.com/2973004/166588528-866aefd7-3aba-4ff1-a119-cd4bae6ce398.png)
`is_union=True`:
![struct_unionTrue](https://user-images.githubusercontent.com/2973004/166588535-69a46b47-6a61-425f-98e1-a4b7a5ce9d53.png)

**Version**<br />
Python-Version: 3.10
opcua-asyncio Version: master branch, 0.9.92 from early May 2022

**Comment by schroeder-** [comment]
Works as expected.
A Union is Null or **ONE** of its Fields. The default value in asyncua is Null. See: https://reference.opcfoundation.org/v104/Core/docs/Part6/5.2.8/

**Comment by danmoser** [comment]
Thanks @schroeder- . I'm sorry for the false flag.
