### ISSUE TITLE
Getting server timestamp

### ISSUE THREAD

**Issue by unregistered33** [FreeOpcUa/opcua-asyncio#880]
Not issue just question. How to get server timestamp for value in datachange notification?
 def datachange_notification(self, node, val, data):
        print("New data change event", node, val)

Thanks!

**Comment by schroeder-** [comment]
The server doens't have to provide ServerTimestamp so the timestamp can be None. But if a timestamp is provided this should work:
```
def datachange_notification(self, node, val, data):
    print('ServerTimeStamp: " , data.monitored_item.Value.ServerTimestamp)
```

**Comment by unregistered33** [comment]
Thanks, it works!
