### ISSUE TITLE
Not enough data left in buffer。

### ISSUE THREAD

**Issue by EvashuangshuangFeng** [FreeOpcUa/opcua-asyncio#883]
Nested structure：

await client.load_type_definitions()
after = await struct.read_value()
---------------------------------------

File "C:\Program Files\Python38\lib\site-packages\asyncua\ua\ua_binary.py", line 73, in unpack
    b = _Bytes.unpack(data)
  File "C:\Program Files\Python38\lib\site-packages\asyncua\ua\ua_binary.py", line 61, in unpack
    return data.read(length)
  File "C:\Program Files\Python38\lib\site-packages\asyncua\common\utils.py", line 59, in read
    raise NotEnoughData(f"Not enough data left in buffer, request for {size}, we have {self._size}")
asyncua.common.utils.NotEnoughData: Not enough data left in buffer, request for 256, we have 95

**Comment by EvashuangshuangFeng** [comment]
@schroeder-  
1. Read structure fails with string datatype.
2. When I delete the string datatype, read structure succeeds, but the value of structure and controller do not match.

2.1 This is value from asyncua
![image](https://user-images.githubusercontent.com/105616897/168712492-155ed111-efc2-46c4-804b-79a7bd5dcae1.png)

2.2  This is value from Uaexpert.
![image](https://user-images.githubusercontent.com/105616897/168712336-1f356166-08f4-4a89-800d-97ba464e1037.png)

**Comment by EvashuangshuangFeng** [comment]
> Looks like a we don't support some special cases in the encoding.
> 
> What server you are running against? Which version of asyncua are you using? (Is it possible to use current master?) Is it possible to get the datatype description of the datatypes in question or as nodeset.xml?

**Comment by oroulet** [comment]
I do not understand is that issue solved?
