### ISSUE TITLE
Reconciliator, has undefined attributes/functions

### ISSUE THREAD

**Issue by vruge** [FreeOpcUa/opcua-asyncio#885]
static code analyse with mypy complains in the following places

- [x] `Reconciliator` has no attribute `hook_mi_request` 

https://github.com/FreeOpcUa/opcua-asyncio/blob/4f48eb2df8d998e8f576779fbae8c5c913fddab5/asyncua/client/ha/reconciliator.py#L323

https://github.com/FreeOpcUa/opcua-asyncio/blob/4f48eb2df8d998e8f576779fbae8c5c913fddab5/asyncua/client/ha/reconciliator.py#L293

- [x] `Reconciliator` has no attribute  `hook_mi_request` 

https://github.com/FreeOpcUa/opcua-asyncio/blob/4f48eb2df8d998e8f576779fbae8c5c913fddab5/asyncua/client/ha/reconciliator.py#L384

- [x] `Reconciliator` has no attribute  `hook_add_to_map`  

https://github.com/FreeOpcUa/opcua-asyncio/blob/4f48eb2df8d998e8f576779fbae8c5c913fddab5/asyncua/client/ha/reconciliator.py#L411

- [x] `Reconciliator` has no attribute  `hook_add_to_map_error`

https://github.com/FreeOpcUa/opcua-asyncio/blob/4f48eb2df8d998e8f576779fbae8c5c913fddab5/asyncua/client/ha/reconciliator.py#L432

related to #878

**Comment by schroeder-** [comment]
I don't know anything about the ha client. For me it looks like debug hooks that are left in the code?

**Comment by ZuZuD** [comment]
These are hooks to easily superclass the HaClient and implement custom logic if needed (i.e: monitoring). I'd recommend to just define these functions with pass to appease the type checker.

Let me know if you need my help with this!
