### ISSUE TITLE
Improving custom structures example

### ISSUE THREAD

**Issue by danmoser** [FreeOpcUa/opcua-asyncio#892]
**Expected behavior**<br />
1. Correct the filename from "amd" to "and" -- ie., from `server-custom-structures-amd-enums.py` to `server-custom-structures-and-enums.py`
2. On line 41, add `datatype` to the enum variable: `valnode = await server.nodes.objects.add_variable(idx, "my_enum", ua.MyEnum.toto, datatype=enode.nodeid)`

**Screenshots**<br />
Without datatype:
![enum2](https://user-images.githubusercontent.com/2973004/169149622-17f67016-5f6f-4199-9455-0be657f035aa.png)

With datatype:
![enum1](https://user-images.githubusercontent.com/2973004/169149632-34331de1-c576-47f2-b459-6abde2c47154.png)

**Version**<br />
opcua-asyncio Version: master branch, 0.9.93 (on `setup.py`)

**Comment by schroeder-** [comment]
Should be fixed in #894
