### ISSUE TITLE
How to report a security issue?

### ISSUE THREAD

**Issue by SharonBrizinov** [FreeOpcUa/opcua-asyncio#902]
We would like to responsibly report on a vulnerability we found in python opcua-asyncio. Where should we send our detailed report?

Additionally I would like to suggest adding a security policy to the repository to help other security researchers reach out to you properly.

Thanks!
Team82 Claroty Research
https://claroty.com/team82/

**Comment by SharonBrizinov** [comment]
@oroulet I know you asked us to describe our findings here, but we once again ask to disclose this privately. Can you share with us an email address? or maybe you can make this Issue a private one?

**Comment by artfire52** [comment]
Hello,
i would like to report what i think is a possible vulnerability. Did you obtain an email address please ?

**Comment by oroulet** [comment]
That software is not secure anyway, it was not written with security in mind and if you only report it to me it will probably get forgotten, so I think that currently the best is to discuss it a discussion or issue
