### ISSUE TITLE
select_clauses_from_evtype, "NodeId" has no attribute "read_browse_name"

### ISSUE THREAD

**Issue by vruge** [FreeOpcUa/opcua-asyncio#909]
static code analyse with mypy complains in the following places:

`"NodeId" has no attribute "read_browse_name"`

- [x] https://github.com/FreeOpcUa/opcua-asyncio/blob/master/asyncua/common/events.py#L176
- [x] https://github.com/FreeOpcUa/opcua-asyncio/blob/master/asyncua/common/events.py#L178

**Comment by schroeder-** [comment]
My bad, added wrong types, will fix it later.
