### ISSUE TITLE
Node.read_value() does not work any more due to recent change in uatypes.py

### ISSUE THREAD

**Issue by CuriousCrook** [FreeOpcUa/opcua-asyncio#928]
**Describe the bug** <br />
When calling Node.read_value() on a property the following error is thrown:
_Exception caught Not enough data in buffer, request of 4, we have 0._

The recent change in uatypes line 953 leads to the described error.

The current code leads to the described error:
```
@dataclass(frozen=True)
class DataValue:
...
    Value: Variant = field(default_factory=Variant)
...
```

The old code works:
```
@dataclass(frozen=True)
class DataValue:
...
    Value: Optional[Variant] = None
...
```

**To Reproduce**<br />
Just call read_value() on a property node,

**Expected behavior**<br />
Read the value of the property node.

**Version**<br />
Python-Version: 3.10.4 <br />
opcua-asyncio Version (e.g. master branch, 0.9):
latest on master

**Comment by oroulet** [comment]
also why does not the tests show any issue? Is that a compatibility issue?

**Comment by schroeder-** [comment]
Between our server and client there is no error, its an interoperability issue, because we now not conforming anymore.

**Comment by oroulet** [comment]
arrg and reverting these changes make conflict everywhere

**Comment by oroulet** [comment]
Can we just revert the line over and it will work?

**Comment by oroulet** [comment]
As per the spec the Variant can be optional. so it must be typed as optional. I do not care about mypy (although it would be nice, but not very important  to make it work)

**Comment by oroulet** [comment]
https://github.com/FreeOpcUa/opcua-asyncio/pull/931

**Comment by schroeder-** [comment]
No problem, I don't need mypy.
