### ISSUE TITLE
asyncua/common/structures104.py", line 284, in _generate_object  doesnt properly sanitize node name

### ISSUE THREAD

**Issue by jmtatsch** [FreeOpcUa/opcua-asyncio#957]
When connecting to a Siemens s7 opcua crashes here on a string within a string:

```
asyncua/common/structures104.py", line 284, in _generate_object
    exec(code, env)
  File "<string>", line 10
    data_type = ua.NodeId.from_string("ns=3;s=DT_"LCB_15x_ActuatorSpeed_B_1"."scInternalCtrl"")
                                                  ^
SyntaxError: invalid syntax

It seems the culprit is using the non pythonized "LCB_15x_ActuatorSpeed_B_1"."scInternalCtrl" instead of _LCB_15x_ActuatorSpeed_B_1_scInternalCtrl_ may be the culprit here?

happens on opcua-asyncio master branch

**Comment by jmtatsch** [comment]
Wow, you are crazy fast. I can hopefully test tomorrow once the machine is back online and will report back.

**Comment by oroulet** [comment]
I am not that fast, you are no the first one to see that issue. so I wrote that stuff several months ago. It would be nice if someone could test it. I am not 100% sure it solves the issue

**Comment by elmovw-evac** [comment]
https://github.com/FreeOpcUa/opcua-asyncio/blob/0d006fc6978138f0fe9b56fc1f2489fcfa4d5d05/asyncua/common/structures104.py#L170-L181

I think I resolved this in my own fork, but I haven't used it much recently. The problem is about generating a valid Python string literal that contains quotes, which is literally the purpose of `repr()`. Adding a `!r` conversion flag to line 179 seemed to fix this for me:

```
    data_type = ua.NodeId.from_string("{data_type.to_string()!r}")
```

...with the output looking something like this:

```python
    data_type = ua.NodeId.from_string('ns=3;s=DT_"ValveOnOff"')
```

Initially, `repr()` fixes the problem by just utilizing single quotes. Any single quotes appearing in the `NodeId` should also get escaped gracefully:

```python
>>> my_nodeid = input()
DT_"Let's prepare for the worst"
>>> print(f"{my_nodeid!r}")
'DT_"Let\'s prepare for the worst"'
```

The Siemens Node ID quote-fest is ugly, but we shouldn't really sanitize it to avoid creating more problems.

**Comment by oroulet** [comment]
Someone tried using repr and that solution had issues. I do not remember why. That is why I made that PR. Does the PR changes something?

**Comment by jmtatsch** [comment]
tried the suggestion of @elmovw-evac because it seems so simple and it fails like this:
`  File "/home/jtatsch/.local/lib/python3.8/site-packages/asyncua-0.9.94-py3.8.egg/asyncua/common/structures104.py", line 284, in _generate_object
    exec(code, env)
  File "<string>", line 28
    awInt: List[ua.<class 'asyncua.ua.uatypes.UInt16'>] = field(default_factory=list)
                   ^
SyntaxError: invalid syntax
`

will look in the pr now

**Comment by jmtatsch** [comment]
pr #784 currently yields this:
```
File "/home/jtatsch/.local/lib/python3.8/site-packages/asyncua-0.9.94-py3.8.egg/asyncua/client/client.py", line 687, in load_data_type_definitions
    return await load_data_type_definitions(self, node, overwrite_existing=overwrite_existing)
  File "/home/jtatsch/.local/lib/python3.8/site-packages/asyncua-0.9.94-py3.8.egg/asyncua/common/structures104.py", line 426, in 
load_data_type_definitions
    env = await _generate_object(dts.name, dts.sdef, data_type=dts.data_type, log_fail=log_ex)
  File "/home/jtatsch/.local/lib/python3.8/site-packages/asyncua-0.9.94-py3.8.egg/asyncua/common/structures104.py", line 289, in _generate_object
    code = make_structure_code(data_type, name, sdef, log_error=log_fail)
  File "/home/jtatsch/.local/lib/python3.8/site-packages/asyncua-0.9.94-py3.8.egg/asyncua/common/structures104.py", line 219, in make_structure_code
    default_value = get_default_value(uatype)
  File "/home/jtatsch/.local/lib/python3.8/site-packages/asyncua-0.9.94-py3.8.egg/asyncua/common/structures104.py", line 143, in get_default_value
    if hasattr(ua, uatype):
TypeError: hasattr(): attribute name must be string
```

**Comment by oroulet** [comment]
ok. simple change that might solve your issue: https://github.com/FreeOpcUa/opcua-asyncio/pull/958

**Comment by jmtatsch** [comment]
```
  File "/home/jtatsch/.local/lib/python3.8/site-packages/asyncua-0.9.94-py3.8.egg/asyncua/client/client.py", line 687, in load_data_type_definitions
    return await load_data_type_definitions(self, node, overwrite_existing=overwrite_existing)
  File "/home/jtatsch/.local/lib/python3.8/site-packages/asyncua-0.9.94-py3.8.egg/asyncua/common/structures104.py", line 414, in load_data_type_definitions
    env = await _generate_object(dts.name, dts.sdef, data_type=dts.data_type, log_fail=log_ex)
  File "/home/jtatsch/.local/lib/python3.8/site-packages/asyncua-0.9.94-py3.8.egg/asyncua/common/structures104.py", line 284, in _generate_object
    exec(code, env)
  File "<string>", line 28
    awInt: List[ua.<class 'asyncua.ua.uatypes.UInt16'>] = field(default_factory=list)
                   ^
SyntaxError: invalid syntax

```

**Comment by schroeder-** [comment]
For this error you need: #954

**Comment by jmtatsch** [comment]
Amazing, with these two changes I can finally browse the s7. Thank you so much @oroulet @schroeder- @elmovw-evac .
