### ISSUE TITLE
Server import_xml performance downgrade from 0.8.4 to 0.9.94

### ISSUE THREAD

**Issue by jsbruglie** [FreeOpcUa/opcua-asyncio#961]
Hello! Following the discussion on Gitter I figured I should summarize my findings an add an example to reproduce the problem.
I've observed that when moving from asyncua 0.8.4 to the latest 0.9.9X the servers take substantially longer to start.

**To Reproduce**<br />

I included a minimal server as well as an example server import file here: [example.zip](https://github.com/FreeOpcUa/opcua-asyncio/files/9090982/example.zip).
The script itself just initializes a server, imports data from a file, starts and stops.

```python
import asyncio
import pathlib
from time import time
from asyncua import Server

cur_dir = pathlib.Path(__file__).parent.resolve()
example_import_xml = cur_dir / "example.xml"

async def main():
    start = time()
    server = Server()
    await server.init()
    server.set_endpoint('opc.tcp://0.0.0.0:4841/freeopcua/server/')
    time_init = time()
    await server.import_xml(path=example_import_xml)
    time_import_xml = time()
    await server.start()
    await server.stop()
    stop = time()

    duration_init = time_init - start
    duration_import_xml = time_import_xml - time_init
    total = stop - start
    print("init {:.3f} s, import {:.3f} s, total {:.3f} s".format(duration_init, duration_import_xml, total))

if __name__ == "__main__":
    asyncio.run(main())
```

**Benchmarks**<br />

|        | init (sec) | import (sec) | total (sec) |
|--------|------------|--------------|-------------|
| 0.8.4  | 1.203      | 2.063        | 3.266       |
| 0.9.94 | 2.359      | 119.655      | 123.062     |

It seems that `import_xml` is now taking close to 60 times more than previously.
I'll add the profiling results in a comment soon.

**Version**<br />
Python-Version:3.9.10 (but also reproduced on 3.10)<br />
opcua-asyncio Version (e.g. master branch, 0.9): 0.9.94 (master)

**Comment by swamper123** [comment]
Hey ho,

I haven't got a solution for your problem, but I want that you keep some things in your mind:

1. Since Jul 8, 2020, many things happened in this repo. Even with the xml_import.
2. XML in combination with Python is mostly slow. Also we switched from lxml to builtin xml.
3. Many checks haven't be made in earlier versions. An for the server unknown XML file can be a wild west thing, which has to be checked in many directions before accepting everything blindly. We don't know if it is an officiall XML or a selfmade one. Even if it is an official one, things can still be difficult sometimes.

I haven't tested your server example, but I still believe you. 
But atm I have no clue how to speed up things, without dropping quality or starting to work on Python core things.

good, working solutions are always welcomed as PR.

**Comment by jsbruglie** [comment]
Hello and thank you for the quick reply!

I understand that quite a few changes have been made, and I've already adapted my test pipeline to reuse servers as much as possible. I'm first trying to pinpoint where most of the time is going, but it's unlikely it will be trivial to improve the performance.
In any case, as promised, the output of `pyinstrument` shows most time is spent adding missing reverse references, ultimately pointing to `server/address_space` as seen in [pyinstrument.txt](https://github.com/FreeOpcUa/opcua-asyncio/files/9091319/pyinstrument.txt).

Perhaps it's possible to somehow reuse previous results and optimize the process?
Will update the issue if I find something.

Cheers!

**Comment by swamper123** [comment]
> Perhaps it's possible to somehow reuse previous results and optimize the process?

This is very very tricky...since the server doesn't know what Nodes are incoming and what references have to be made.
And you can't guarante that each Node was correctly created & implemented and reuse them for following Nodes....and many more minor details on the way. :/
If sb. gets that thing optimized well, he earns my respect. ^^

**Comment by jsbruglie** [comment]
I haven't measured it, but I do this at an earlier stage, in order to produce these XML files in the first place, and I have the impression it's much faster. The problem then is I either produce a hardcoded script or create yet another format to represent the server tree and parse it afterwards. Indeed, it's an alternative, to just save the necessary data in a much more restricted format and then have a small script read it and call `add_variable` and `add__object` accordingly. Was trying to not come up with another file format since the XML already existed, but I see now that the implementation has changed quite a bit, and it will be hard to make it faster without losing features.

**Comment by oroulet** [comment]
If you want to track down the issue you need to set up an example as simple as possible. In your example the first thing to remove is obviously the XML import.

**Comment by jsbruglie** [comment]
I understand that the file itself could have been simpler, but as far as I understand, the issue is the performance downgrade when importing the file, and the profiler indicates that this is where the time is spent. The code for `xmlimporter::_add_missing_reverse_references` does have several nested for loops, and while I guess that there may be some redundant work being done, it would be a pain to rewrite it without introducing bugs or worsening it in some other way.

**Comment by elmovw-evac** [comment]
Haha - I had just submitted #963 yesterday without having read this discussion at all. I identified and fixed the two bottlenecks back in May. OPC UA is quite new to me and I'm definitely not confident whether my solution is complete!

**Comment by jsbruglie** [comment]
Closing this issue, as @elmovw-evac has fixed the issue and @oroulet merged it to master. Thanks again!
