### ISSUE TITLE
Subscribing to events requires TypeDefinitionId in some cases

### ISSUE THREAD

**Issue by deeTEEcee** [FreeOpcUa/opcua-asyncio#964]
In my fork of python-opcua for both SelectClauses and WhereClauses, I had to define TypeDefinitionId with the BaseEventType.
```
op.TypeDefinitionId = NodeId(identifier=ua.ObjectIds.BaseEventType, namespaceidx=0, nodeidtype=NodeIdType.Numeric)
```

Without this, subscribing to events was broken. The server would return the same error message for all the select clauses `BadTypeDefinitionError: "'"The type definition node id does not reference an appropriate type node."'`

**Comment by deeTEEcee** [comment]
Any thoughts on this? 

I'm curious if adding this to the call would be a problem for existing event subscriptions that already work. The [docs](https://reference.opcfoundation.org/v105/Core/docs/Part4/7.22.3/) says a bit about TypeDefinitionId here.

**Comment by schroeder-** [comment]
Setting TypeDefinitionId to ua.ObjectIds.BaseEventType should be done anyway. 
In open62541 a empty TypeDefinitionId is not allowed.
https://github.com/open62541/open62541/blob/cfeeeedf423e7d4cbab00162f34561b7a2c54cb0/src/server/ua_subscription_events_filter.c#L1064-L1067
