### ISSUE TITLE
how can i connect more then one server use  opcua-asyncio

### ISSUE THREAD

**Issue by hotbbsun** [FreeOpcUa/opcua-asyncio#99]
with the code :
loop = asyncio.get_event_loop()
loop.run_until_complete(one())

I can not add  an other one

hope help;
tks

**Comment by oroulet** [comment]
With gather or wait. Read an Asyncio tutorial

**Comment by hotbbsun** [comment]
thanks
it works

loop = asyncio.get_event_loop()    
for opcRune in ListOPCServer:
        task1 = loop.create_task(myOPCService(opcUrl))
        print("gogogo",opcRune['url'])
 loop.run_forever()
