### ISSUE TITLE
Labview OPC server 2016 

### ISSUE THREAD

**Issue by omidfathi** [FreeOpcUa/opcua-asyncio#995]
Hi , 
I need to connect to a labview opc server, and I can't find any NameSpaces or Identifier for nodes.
Could you tell me how can I get value from this server and it's nodes ?
![Capture](https://user-images.githubusercontent.com/89828328/184406817-3e258026-e747-4021-a3c3-dae096ad4390.PNG)

**Comment by schroeder-** [comment]
I don't know anything about the labview opc server. You can try to browse the server with a diagnostic clients like UAExpert and find the tags there. They display the NodeId to use in your client code.
